export const CODE_LINES = [
  'import polars',
  'df = polars.read_csv("./strava_data/activities-2026-05-04.csv")',
  '# filter by activities that mention bad apple',
  'df = df.filter(df["name"].str.contains("Bad Apple"))',
  'total_distance = df["distance_m"].sum()',
  'total_time = df["time_s"].sum()',
  'print(f"Total distance: {total_distance/1000:.2f} km")',
  'print(f"Total time: {total_time/3600:.2f} hours")',
  '# gps helper functions',
  'import utm',
  'import math',
  'import datetime',
  'toronto_bl = 43.644057, -79.418834',
  'toronto_tr = 43.670315, -79.386814',
  'def x_y_to_gps(x, y, width, height, bottom_left_lat_long=toronto_bl, top_right_lat_long=toronto_tr, ',
  '               angle_degrees=0, skew_x_degrees=0, skew_y_degrees=0, x_scale=1.0, y_scale=1.0):',
  '    """',
  '    Convert a single x,y coordinate to GPS coordinates with support for transformation.',
  '    Args:',
  '        x, y: Coordinates in the original space',
  '        width, height: Dimensions of the original space',
  '        bottom_left_lat_long: GPS coordinates of bottom left corner',
  '        top_right_lat_long: GPS coordinates of top right corner',
  '        angle_degrees: Rotation angle in degrees (clockwise from normal orientation)',
  '        skew_x_degrees: Horizontal skew angle in degrees',
  '        skew_y_degrees: Vertical skew angle in degrees',
  '        x_scale: Scaling factor for x-coordinates',
  '        y_scale: Scaling factor for y-coordinates',
  '    Returns:',
  '        (latitude, longitude) tuple',
  '    """',
  '    # Convert bottom-left and top-right lat/lon to UTM',
  '    bl_lat, bl_lon = bottom_left_lat_long',
  '    tr_lat, tr_lon = top_right_lat_long',
  '    bl_easting, bl_northing, bl_zone_number, bl_zone_letter = utm.from_latlon(bl_lat, bl_lon)',
  '    tr_easting, tr_northing, tr_zone_number, tr_zone_letter = utm.from_latlon(tr_lat, tr_lon)',
  '    # Ensure both points are in the same UTM zone',
  '    if bl_zone_number != tr_zone_number or bl_zone_letter != tr_zone_letter:',
  '        raise ValueError("The two points are not in the same UTM zone")',
  '    # Calculate the UTM coordinates of the point based on x, y, width, and height',
  '    x_ratio = x / width',
  '    y_ratio = y / height',
  '    # Center the coordinate system (move to origin)',
  '    x_centered = x_ratio - 0.5',
  '    y_centered = y_ratio - 0.5',
  '    # Apply scaling',
  '    x_transformed = x_centered * x_scale',
  '    y_transformed = y_centered * y_scale',
  '    # Apply skew transformations',
  '    if skew_x_degrees != 0:',
  '        # Horizontal skew (shifts x based on y position)',
  '        skew_x_rad = math.radians(skew_x_degrees)',
  '        x_transformed += y_transformed * math.tan(skew_x_rad)',
  '    if skew_y_degrees != 0:',
  '        # Vertical skew (shifts y based on x position)',
  '        skew_y_rad = math.radians(skew_y_degrees)',
  '        y_transformed += x_transformed * math.tan(skew_y_rad)',
  '    # Apply rotation if needed',
  '    if angle_degrees != 0:',
  '        angle_radians = math.radians(angle_degrees)',
  '        x_rot = x_transformed * math.cos(angle_radians) - y_transformed * math.sin(angle_radians)',
  '        y_rot = x_transformed * math.sin(angle_radians) + y_transformed * math.cos(angle_radians)',
  '        x_transformed = x_rot',
  '        y_transformed = y_rot',
  '    # Move back from origin',
  '    x_ratio = x_transformed + 0.5',
  '    y_ratio = y_transformed + 0.5',
  '    # Calculate the interpolated UTM coordinates',
  '    point_easting = bl_easting + (tr_easting - bl_easting) * x_ratio',
  '    point_northing = bl_northing + (tr_northing - bl_northing) * y_ratio',
  '    # Convert the UTM coordinates back to lat/lon',
  '    point_lat, point_lon = utm.to_latlon(point_easting, point_northing, bl_zone_number, bl_zone_letter)',
  '    return point_lat, point_lon',
  'def create_track_from_points(points, width, height, **kwargs):',
  '    """',
  '    Create a GPS track from a list of (x,y) points.',
  '    Args:',
  '        points: List of (x, y) tuples in pixel coordinates',
  '        width, height: Dimensions of the coordinate space',
  '        **kwargs: Additional parameters to pass to x_y_to_gps',
  '    Returns:',
  '        List of (latitude, longitude) tuples',
  '    """',
  '    gps_points = []',
  '    for x, y in points:',
  '        lat, lon = x_y_to_gps(x, y, width, height, **kwargs)',
  '        gps_points.append((lat, lon))',
  '    return gps_points',
  'def export_to_gpx(gps_points: list[tuple[float, float]], output_file="track.gpx", name="Generated Track", description="Track generated from coordinates"):',
  '    """',
  '    Export a list of GPS coordinates to a GPX file.',
  '    Args:',
  '        gps_points: List of (latitude, longitude) tuples',
  '        output_file: Path to save the output GPX file',
  '        name: Name of the track',
  '        description: Description of the track',
  '    Returns:',
  '        Path to the saved GPX file',
  '    """',
  '    # Create GPX header',
  '    gpx_content = [',
  '        \'<?xml version="1.0" encoding="UTF-8"?>\',',
  '        \'<gpx version="1.1" creator="GPS.py"\',',
  '        \'     xmlns="http://www.topografix.com/GPX/1/1"\',',
  '        \'     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\',',
  '        \'     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">\',',
  '        f\'  <metadata>\',',
  '        f\'    <name>{name}</name>\',',
  '        f\'    <desc>{description}</desc>\',',
  '        f\'    <time>{datetime.datetime.now().isoformat()}Z</time>\',',
  '        f\'  </metadata>\',',
  '        \'  <trk>\',',
  '        f\'    <name>{name}</name>\',',
  '        \'    <trkseg>\'',
  '    # Add track points',
  '    for lat, lon in gps_points:',
  '        gpx_content.append(f\'      <trkpt lat="{lat}" lon="{lon}"></trkpt>\')',
  '    # Close the GPX structure',
  '    gpx_content.extend([',
  '        \'    </trkseg>\',',
  '        \'  </trk>\',',
  '        \'</gpx>\'',
  '    # Write to file',
  '    with open(output_file, \'w\') as f:',
  '        f.write(\'\\n\'.join(gpx_content))',
  '    return output_file',
  '#  to run: delete .strava.secrets, run again, authorize in the browser, paste the url',
  'import time',
  'from pathlib import Path',
  'from strava_client.client import StravaClient',
  'from strava_client.models.api import StravaActivity',
  'from datetime import datetime',
  'import polars',
  'from dotenv import load_dotenv',
  'load_dotenv()',
  '# delete the .strava.secrets file to reset authentication flow because its always expired seemingly',
  'secrets_file = Path(".strava.secrets")',
  'if secrets_file.exists():',
  '    secrets_file.unlink()',
  'client = StravaClient(scopes=["activity:read_all", "profile:read_all", "read_all"])',
  'activities: list[StravaActivity] = client.get_activities(after=datetime(2025, 5, 18), per_page=200) # I started on May 18th',
  'print(f"Found {len(activities)} activities.")',
  'df = polars.DataFrame()',
  'for activity in activities:',
  '    latest_date = activity.start_date_local.strftime("%Y-%m-%d")',
  '    url = f"https://www.strava.com/activities/{activity.id}"',
  '    data = dict(',
  '        date=activity.start_date_local.strftime("%Y-%m-%d"),',
  '        name=activity.name, ',
  '        time_s=activity.moving_time,',
  '        distance_m=activity.distance,',
  '        url=url,',
  '    #  max 100 rwquests every 15 minutes, so need 9 second interval to not get rate limited when over 100 activities',
  '    activity_detailed = client.get_activity_detailed(activity.id)',
  '    polyline = activity_detailed.map.polyline',
  '    print(f"Got polyline for {activity.name}: {polyline}")',
  '    data.update({"polyline": polyline})',
  '    print(f"Saving {activity.name}: {url} to csv.")',
  '    time.sleep(10)',
  '    df = df.vstack(polars.DataFrame(data, orient="row"))',
  '# include current date in ',
  'output_folder = Path("strava_data")',
  'output_folder.mkdir(exist_ok=True)',
  'df.write_csv(str(output_folder / f"activities-{latest_date}.csv"))',
  'import cv2',
  'from pathlib import Path',
  '# Open the input video',
  'cap = cv2.VideoCapture("badapple-small.mp4")',
  '# Get original video properties',
  'original_fps = cap.get(cv2.CAP_PROP_FPS)',
  'frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))',
  'width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))',
  'height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))',
  'print(f"Video properties: {width}x{height}")',
  'print(f"Original FPS: {original_fps}, Frame Count: {frame_count}")',
  '# Desired FPS',
  'desired_fps = 2',
  '# Calculate the frame interval to achieve the desired FPS',
  'frame_interval = int(original_fps / desired_fps)',
  '# Initialize the video writer',
  'output_folder = Path("fps_videos")',
  'output_folder.mkdir(exist_ok=True)',
  'output_file = output_folder / f"badapple-small-{desired_fps}fps.mp4"  # Changed extension to .mp4',
  'writer = cv2.VideoWriter(output_file, cv2.VideoWriter_fourcc(*\'H264\'), desired_fps, (width, height))',
  '# Process the video',
  'frame_idx = 0',
  'output_frame_count = 0',
  'while True:',
  '    ret, frame = cap.read()',
  '    # if frame_idx > 16*original_fps:',
  '    #     break',
  '    if not ret:',
  '        break',
  '    # Write every nth frame based on the interval',
  '    if frame_idx % frame_interval == 0:',
  '        writer.write(frame)',
  '        output_frame_count += 1',
  '    frame_idx += 1',
  '# Release resources',
  'cap.release()',
  'writer.release()',
  'print(f"Expected number of frames: {frame_count // frame_interval}")',
  'print(f"Output video saved as {output_file} with {output_frame_count} frames at {desired_fps} FPS.")',
  '# streamlit app to generate a GPX file from a single frame of a video',
  '# used this for my Toronto trip',
  '# streamlit run src/single_frame_gpx.py',
  'from gps import x_y_to_gps, export_to_gpx',
  'from archived.map_to_image import get_map_image',
  'import cv2',
  'import numpy as np',
  'import streamlit as st',
  'import tempfile',
  'from dotenv import load_dotenv',
  'import os',
  'load_dotenv()',
  '# make a list of x, y that make a rectangle from 0,0 to 480x360',
  'cap = cv2.VideoCapture("badapple-small.mp4")',
  '# Get total number of frames and framerate',
  'total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))',
  'frame_rate = cap.get(cv2.CAP_PROP_FPS)',
  'print(f"Total number of frames: {total_frames}")',
  'print(f"Framerate: {frame_rate} FPS")',
  'default_bottom_left_lat_long = os.environ["BOTTOM_LEFT_LAT_LONG"]',
  'default_top_right_lat_long = os.environ["TOP_RIGHT_LAT_LONG"]',
  'def bad_apple_contour_xy_list(frame_number):',
  '    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)',
  '    ret, frame = cap.read()',
  '    xy_list = []',
  '    # Convert frame to grayscale',
  '    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)',
  '    # Apply threshold to get binary image',
  '    _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)',
  '    # Find contours',
  '    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)',
  '    # Use the largest contour',
  '    if contours:',
  '        largest_contour = max(contours, key=cv2.contourArea)',
  '        # Extract points from the contour',
  '        for point in largest_contour:',
  '            x, y = point[0]',
  '            xy_list.append((x, 360 - y))',
  '    return xy_list',
  'frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))',
  '# Initialize session state',
  'if \'gps_list\' not in st.session_state:',
  '    st.session_state.gps_list = []',
  'if \'img_path\' not in st.session_state:',
  '    st.session_state.img_path = "map.png"',
  'def on_form_submit():',
  '    xy_list = bad_apple_contour_xy_list(st.session_state.frame_number)',
  '    gps_list = [x_y_to_gps(x, y, 480, 360, ',
  '                          bottom_left_lat_long=st.session_state.bottom_left_lat_long,',
  '                          top_right_lat_long=st.session_state.top_right_lat_long, ',
  '                          angle_degrees=st.session_state.angle,',
  '                          skew_y_degrees=st.session_state.skew_y,',
  '                          skew_x_degrees=st.session_state.skew_x,',
  '                          x_scale=st.session_state.x_scale,',
  '                          y_scale=st.session_state.y_scale) for x, y in xy_list]',
  '    st.session_state.gps_list = gps_list',
  '    st.session_state.img_path = get_map_image(gps_list, 1920, 1080, zoom=st.session_state.zoom)',
  'st.set_page_config(page_title="Bad Apple Strava Generator", layout="wide")',
  'st.write("## Bad Apple Strava Generator")',
  'col1, col2 = st.columns([1, 3])',
  'with col1:',
  '    with st.form("badapple-strava-form"):',
  '        st.number_input("Frame Number", min_value=0, max_value=frame_count - 1, value=235, key="frame_number")',
  '        st.slider("Angle", -180.0, 180.0, 0.0, step=0.1, key="angle")',
  '        st.slider("Skew Y", -10.0, 10.0, 0.0, step=0.1, key="skew_y")',
  '        st.slider("Skew X", -10.0, 10.0, 0.0, step=0.1, key="skew_x")',
  '        st.slider("X Scale", 0.1, 2.0, 1.0, step=0.1, key="x_scale")',
  '        st.slider("Y Scale", 0.1, 2.0, 0.9, step=0.1, key="y_scale")',
  '        st.slider("Map zoom", 1, 20, 20, key="zoom")',
  '        bottom_left = st.text_input("Bottom Left Lat, Long", default_bottom_left_lat_long)',
  '        top_right = st.text_input("Top Right Lat, Long", default_top_right_lat_long)',
  '        st.session_state.bottom_left_lat_long = tuple(map(float, map(str.strip, bottom_left.split(","))))',
  '        st.session_state.top_right_lat_long = tuple(map(float, map(str.strip, top_right.split(","))))',
  '        st.form_submit_button("Generate Map", on_click=on_form_submit)',
  'col2.image(st.session_state.img_path)',
  'if st.session_state.gps_list:',
  '    output_gpx_path = tempfile.gettempdir() + "/track.gpx"',
  '    export_to_gpx(st.session_state.gps_list, output_file=output_gpx_path, ',
  '                 name="Bad Apple Track Frame " + str(st.session_state.frame_number))',
  '    col2.write("Download this GPX and upload it to a Strava route (paid feature, use the free trial to upload all at once.)")',
  '    with open(output_gpx_path, "rb") as gpx_file:',
  '        gpx_data = gpx_file.read()',
  '        col2.download_button("Download GPX", gpx_data, file_name="track.gpx", ',
  '                           mime="application/gpx+xml", on_click="ignore")',
  '# take in json file and gps parameters and output gpx files',
  'import os',
  'from dotenv import load_dotenv',
  'from pathlib import Path',
  'import shutil',
  'import json',
  'from gps import x_y_to_gps, export_to_gpx',
  'load_dotenv()',
  'output_path = Path("final")',
  'shutil.rmtree(output_path, ignore_errors=True)',
  'os.makedirs(output_path, exist_ok=True)',
  'bottom_left_lat_long = [float(x) for x in os.environ["BOTTOM_LEFT_LAT_LONG"].split(",")]',
  'top_right_lat_long = [float(x) for x in os.environ["TOP_RIGHT_LAT_LONG"].split(",")]',
  '# Default parameters from app.py',
  'angle = 0.0',
  'skew_y = 0.0',
  'skew_x = 0.0',
  'x_scale = 1.0',
  'y_scale = 0.9',
  '# Load contours from JSON',
  'def load_contours(skip_frames=15):',
  '    contours_file = Path(f\'contours-{skip_frames}.json\')',
  '    with open(contours_file) as f:',
  '        return json.load(f)',
  'contours = load_contours(skip_frames=15)',
  'for key, xy_list in contours.items():',
  '    # Convert to GPS coordinates',
  '    gps_list = [x_y_to_gps(x, y, 480, 360,',
  '                           bottom_left_lat_long=bottom_left_lat_long,',
  '                           top_right_lat_long=top_right_lat_long,',
  '                           angle_degrees=angle,',
  '                           skew_y_degrees=skew_y,',
  '                           skew_x_degrees=skew_x,',
  '                           x_scale=x_scale,',
  '                           y_scale=y_scale) for x, y in xy_list]',
  '    # Export to GPX',
  '    output_file = output_path / f"{key}.gpx"',
  '    export_to_gpx(gps_list, output_file=output_file, name=key, description=f"Bad apple frame {key}")',
  '    print(f"Exported {key} to {output_file}")',
  'import csv',
  'import json',
  'import re',
  'from pathlib import Path',
  'def main():',
  '    csv_path = Path("strava_data/activities-2026-05-04.csv")',
  '    output_path = Path("strava_data/bad_apple_activities.json")',
  '    activities = []',
  '    with open(csv_path) as f:',
  '        reader = csv.DictReader(f)',
  '        for row in reader:',
  '            name = row["name"]',
  '            if "Bad Apple" not in name:',
  '                continue',
  '            match = re.search(r"\\d+", name)',
  '            frame = int(match.group()) if match else None',
  '            activities.append({',
  '                "frame": frame,',
  '                "distance_m": float(row["distance_m"]),',
  '                "time_s": int(row["time_s"]),',
  '                "polyline": row["polyline"],',
  '    with open(output_path, "w") as f:',
  '        json.dump(activities, f, indent=2)',
  '    print(f"Exported {len(activities)} activities to {output_path}")',
  'if __name__ == "__main__":',
  '    main()',
  'import streamlit as st',
  'import cv2',
  'import numpy as np',
  'import json',
  'from pathlib import Path',
  'import os',
  'st.set_page_config(page_title="Bad Apple Contour Editor", layout="wide")',
  '# Load contours from JSON',
  'def load_contours(skip_frames=15):',
  '    contours_file = Path(f\'contours-{skip_frames}.json\')',
  '    if contours_file.exists():',
  '        with open(contours_file) as f:',
  '            return json.load(f)',
  '    return {}',
  'def save_contours(contours, skip_frames=15):',
  '    temp_file = f\'contours-{skip_frames}.json.tmp\'',
  '    try:',
  '        with open(temp_file, \'w\') as f:',
  '            json.dump(contours, f)',
  '        os.replace(temp_file, f\'contours-{skip_frames}.json\')',
  '    except Exception as e:',
  '        if os.path.exists(temp_file):',
  '            os.remove(temp_file)',
  '        raise e',
  'def find_contours_with_params(frame, mode, method, invert=False):',
  '    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)',
  '    _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)',
  '    if invert:',
  '        thresh = cv2.bitwise_not(thresh)',
  '    contours, _ = cv2.findContours(thresh, mode, method)',
  '    if not contours:',
  '        return []',
  '    # Return all contours instead of just the largest one',
  '    return [[(point[0][0], 360 - point[0][1]) for point in contour] for contour in contours]',
  'def render_points(xy_lists, selected_indices=None):',
  '    if not xy_lists:',
  '        return np.full((360, 480, 3), (255, 255, 255), dtype=np.uint8)',
  '    img = np.full((360, 480, 3), (255, 255, 255), dtype=np.uint8)',
  '    if selected_indices is None:',
  '        selected_indices = range(len(xy_lists))',
  '    for idx in selected_indices:',
  '        print(f"{xy_lists[idx]}")',
  '        for x, y in xy_lists[idx]:',
  '            cv2.circle(img, (int(x), int(360-y)), 1, (0, 0, 0), -1)',
  '    return img',
  '# App',
  'st.title("Bad Apple Contour Editor")',
  'skip_frames = 15',
  'frame_idx = st.number_input("Frame Index", min_value=0, step=1)',
  'actual_frame = frame_idx * skip_frames',
  'st.write(f"Frame number: {actual_frame}")',
  '# Load video and contours',
  'cap = cv2.VideoCapture("badapple-small.mp4")',
  'contours = load_contours(skip_frames)',
  '# Set up columns',
  'col1, col2, col3 = st.columns(3)',
  'with col1:',
  '    st.header("Original Frame & Current Contour")',
  '    cap.set(cv2.CAP_PROP_POS_FRAMES, actual_frame)',
  '    ret, frame = cap.read()',
  '    if ret:',
  '        st.image(frame,  caption="Original Frame")',
  '    if str(actual_frame) in contours:',
  '        current_points = contours[str(actual_frame)]',
  '        current_img = render_points([current_points])',
  '        st.image(current_img, caption="Current Contour")',
  '    else:',
  '        st.write("No contour data for this frame")',
  'with col2:',
  '    st.header("New Contour")',
  '    if ret:',
  '        # Contour parameters',
  '        st.subheader("Contour Parameters")',
  '        invert = st.checkbox("Invert Image")',
  '        modes = {',
  '            "RETR_EXTERNAL": cv2.RETR_EXTERNAL,',
  '            "RETR_LIST": cv2.RETR_LIST,',
  '            "RETR_TREE": cv2.RETR_TREE',
  '        methods = {',
  '            "CHAIN_APPROX_NONE": cv2.CHAIN_APPROX_NONE,',
  '            "CHAIN_APPROX_SIMPLE": cv2.CHAIN_APPROX_SIMPLE',
  '        mode = st.selectbox("Contour Mode", list(modes.keys()))',
  '        method = st.selectbox("Contour Method", list(methods.keys()))',
  '        # Generate new contours',
  '        all_contours = find_contours_with_params(frame, modes[mode], methods[method], invert)',
  '        # sort contours by length',
  '        all_contours.sort(key=len, reverse=True) # keep 10 longest contours',
  '        all_contours = all_contours[:10]',
  '        # Contour selection',
  '        st.subheader("Select Contours")',
  '        selected_indices = []',
  '        for i, contour in enumerate(all_contours):',
  '            if st.checkbox(f"Contour {i} ({len(contour)} points)", key=f"contour_{i}", value=i==0):',
  '                selected_indices.append(i)',
  '        # Preview selected contours',
  'with col3:',
  '        if selected_indices:',
  '            new_img = render_points(all_contours, selected_indices)',
  '            st.image(new_img, caption="Selected Contours")',
  '            if st.button("Save Selected Contours"):',
  '                # Combine selected contours into one list',
  '                combined_points = []',
  '                for idx in selected_indices:',
  '                    intified = [(int(x), int(y)) for x, y in all_contours[idx]]',
  '                    combined_points.extend(intified)',
  '                contours[str(actual_frame)] = combined_points',
  '                save_contours(contours, skip_frames)',
  '                st.success("Contours saved!")',
  '                st.rerun()',
  '        else:',
  '            st.write("Select at least one contour to preview and save")',
  'cap.release()',
  '# in one shot, convert bad apple contours to gpx files',
  'from gps import x_y_to_gps, export_to_gpx',
  'from archived.map_to_image import get_map_image',
  'import cv2',
  'import os',
  'import numpy as np',
  'from dotenv import load_dotenv',
  'import shutil',
  'import json',
  'load_dotenv()',
  'skip_frames = 15',
  'out_dir = f"gpx-{skip_frames}"',
  'points_dir = f"points-{skip_frames}"',
  'frames_dir = f"frames-{skip_frames}"',
  '# delete old files',
  'shutil.rmtree(out_dir, ignore_errors=True)',
  'shutil.rmtree(points_dir, ignore_errors=True)',
  'shutil.rmtree(frames_dir, ignore_errors=True)',
  'os.makedirs(out_dir, exist_ok=True)',
  'os.makedirs(points_dir, exist_ok=True)',
  'os.makedirs(frames_dir, exist_ok=True)',
  '# park coordinates from app.py',
  'bottom_left_lat_long = [float(x) for x in os.environ["BOTTOM_LEFT_LAT_LONG"].split(",")]',
  'top_right_lat_long = [float(x) for x in os.environ["TOP_RIGHT_LAT_LONG"].split(",")]',
  '# Default parameters from app.py',
  'angle = 0.0',
  'skew_y = 0.0',
  'skew_x = 0.0',
  'x_scale = 1.0',
  'y_scale = 0.9',
  'cap = cv2.VideoCapture("badapple-small.mp4")',
  'total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))',
  'def find_contours_with_params(thresh, mode, method):',
  '    contours, _ = cv2.findContours(thresh, mode, method)',
  '    if not contours:',
  '        return []',
  '    largest_contour = max(contours, key=cv2.contourArea)',
  '    return [(point[0][0], 360 - point[0][1]) for point in largest_contour]',
  'def bad_apple_contour_xy_list(frame_number):',
  '    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)',
  '    ret, frame = cap.read()',
  '    # Convert frame to grayscale',
  '    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)',
  '    # Apply threshold to get binary image',
  '    _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)',
  '    # Try different contour parameters',
  '    contour_params = [',
  '        (cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE),',
  '        (cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE),',
  '        (cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE),',
  '        (cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)',
  '    # Get all possible contour lists',
  '    contour_lists = [',
  '        find_contours_with_params(thresh, mode, method)',
  '        for mode, method in contour_params',
  '    inverted = cv2.bitwise_not(thresh)',
  '    contour_lists.extend([',
  '        find_contours_with_params(inverted, mode, method)',
  '        for mode, method in contour_params',
  '    # Choose the list with the most points',
  '    best_contour_list = max(contour_lists, key=len, default=[])',
  '    print(f"Frame {frame_number}: Found {len(best_contour_list)} points")',
  '    return best_contour_list, frame',
  'def render_points(xy_list):',
  '    # Create a white background image',
  '    img = np.full((360, 480, 3), (255, 255, 255), dtype=np.uint8)',
  '    # Draw black points',
  '    for x, y in xy_list:',
  '        cv2.circle(img, (int(x), int(360-y)), 1, (0, 0, 0), -1)',
  '    return img',
  '# Store all contours in a dictionary',
  'all_contours = {}',
  '# Process frames in increments of skip_frames',
  'for frame in range(0, total_frames, skip_frames):',
  '    xy_list, frame_img = bad_apple_contour_xy_list(frame)',
  '    # convert numpy int to int',
  '    frame_img = cv2.cvtColor(frame_img, cv2.COLOR_BGR2RGB)',
  '    # Render and save visualization',
  '    cv2.imwrite(f"{frames_dir}/{frame}.png", frame_img)',
  '    img = render_points(xy_list)',
  '    cv2.imwrite(f"{points_dir}/{frame}.png", img)',
  '    gps_list = [x_y_to_gps(x, y, 480, 360,',
  '                          bottom_left_lat_long=bottom_left_lat_long,',
  '                          top_right_lat_long=top_right_lat_long,',
  '                          angle_degrees=angle,',
  '                          skew_y_degrees=skew_y,',
  '                          skew_x_degrees=skew_x,',
  '                          x_scale=x_scale,',
  '                          y_scale=y_scale) for x, y in xy_list]',
  '    output_path = f"{out_dir}/{frame}.gpx"',
  '    export_to_gpx(gps_list, output_file=output_path, ',
  '                 name=f"Bad Apple Track Frame {frame}")',
  '    print(f"Exported frame {frame} to {output_path} and rendered visualization")',
  '    xy_list = [(int(x), int(y)) for x, y in xy_list]',
  '    all_contours[str(frame)] = xy_list',
  '# Save all contours to a single JSON file after the loop',
  'with open(f\'contours-{skip_frames}.json\', \'w\') as f:',
  '    json.dump(all_contours, f)',
  'cap.release()',
  'import folium',
  'from selenium import webdriver',
  'from selenium.webdriver.chrome.options import Options',
  'import time',
  'import tempfile',
  'def calculate_bounding_box(coordinates):',
  '    """Calculate the bounding box of the GPS coordinates."""',
  '    min_lat = min(coord[0] for coord in coordinates)',
  '    max_lat = max(coord[0] for coord in coordinates)',
  '    min_lon = min(coord[1] for coord in coordinates)',
  '    max_lon = max(coord[1] for coord in coordinates)',
  '    return min_lat, max_lat, min_lon, max_lon',
  'def get_map_image(coordinates, width, height, zoom=15):',
  '    """Generate a map image using Folium and Selenium."""',
  '    min_lat, max_lat, min_lon, max_lon = calculate_bounding_box(coordinates)',
  '    center_lat = (min_lat + max_lat) / 2',
  '    center_lon = (min_lon + max_lon) / 2',
  '    m = folium.Map(location=[center_lat, center_lon], zoom_start=zoom)',
  '    folium.PolyLine(coordinates, color="red", weight=2.5, opacity=0.8).add_to(m)',
  '    # Save map to a temporary file',
  '    with tempfile.NamedTemporaryFile(mode="w+", suffix=".html", delete=False) as tmp:',
  '        m.save(tmp.name)',
  '        tmp_name = tmp.name',
  '    # Use Selenium to capture the map as an image',
  '    options = Options()',
  '    options.add_argument("--headless")',
  '    driver = webdriver.Chrome(options=options)',
  '    driver.set_window_size(width, height)',
  '    driver.get(f"file://{tmp_name}")',
  '    time.sleep(2)  # Wait for the map to load',
  '    temp_folder = tempfile.mkdtemp()',
  '    file_name = f"{temp_folder}/map.png"',
  '    driver.save_screenshot(file_name)',
  '    driver.quit()',
  '    return file_name',
  'if __name__ == "__main__":',
  '    get_map_image([(37.39039905303744, -122.06092554900069), (37.39027491874953, -122.06155586811948)], 800, 600)'
];
