export const CODE_LINES = [
  '    No check is performed to ensure ``a_min < a_max``.',
  '           [3, 3, 3, 4, 4, 4]])',
  '        roll. The following table describes how negative values of ``start``',
  '    See Also',
  '    >>> np.ones_like(x)',
  '        Boolean indicating whether to include the initial value (zeros) as',
  '    array([[3, 0, 0],',
  '    Raises',
  '        return _concatenate(arrs, axis=-(max_depth-depth))',
  '    axes are permuted (see Examples). If axes are not provided, then',
  '    >>> import numpy as np',
  '    """',
  '    empty : Return a new uninitialized array.',
  '    truthful if it is nonzero, whereas any string is considered',
  '        else:',
  '    mode : {\'raise\', \'wrap\', \'clip\'}, optional',
  '        kwargs[\'keepdims\'] = keepdims',
  '    slices: list of tuple of slices',
  'def ones_like(',
  '            self.offset = None',
  '    if not (0 <= start < n + 1):',
  '        Also allow scalars for indices.',
  '        Elements to compare for the minimum. See `~numpy.ufunc.reduce`',
  '    else:',
  '    Returns',
  '    n = a.ndim',
  '    array([-1,  3])',
  '    ones_like : Return an array of ones with shape and type of input.',
  '    Shape consistent means they are either the same shape, or one input array',
  '    Examples',
  '        If `a` is 2-D, the sum along the diagonal is returned.  If `a` has',
  '    return result.astype(dtype, copy=False)',
  '                      in row-major order.',
  '        size changes when `endpoint` is False.',
  'import warnings',
  '    >>> np.tensordot(a, A, ((0, 1), (0, 1)))',
  '    Perform an indirect partition along the given axis using the',
  '                                                 self._nfields)]',
  '        .. versionadded:: 1.20.0',
  '    # complex and another is negative and log would produce NaN otherwise.',
  '    array([[0, 1, 2, 3],',
  '    dtype = promote_types(a.dtype, b.dtype)',
  '    array([2.  , 2.25, 2.5 , 2.75, 3.  ])',
  '        If the default value is passed, then `keepdims` will not be',
  '           [13, 14, 15]])',
  '    argsort : Full indirect sort.',
  '@array_function_dispatch(_full_like_dispatcher)',
  '    Equivalently:',
  '    a = concatenate((a,) * repeats)[:new_size]',
  '    sub-arrays thereof) have their ``__nonzero__()`` or ``__bool__()``',
  '    a : array_like',
  '    Returns true if the only way to set the docstring of `obj` from python is',
  '    if start < 0:',
  'def find_duplicate(list):',
  '                y = y * delta',
  '    0.0',
  '    >>> np.logspace(2.0, 3.0, num=4)',
  '    if isinstance(ret, mu.ndarray):',
  '        try:',
  '    if not equal:',
  '    (2, 1, 4)',
  '        Type of the returned array, as well as of the accumulator in which',
  '    out : ndarray',
  '                          keepdims=keepdims, initial=initial, where=where)',
  '        if res:',
  '    # necessary because np.exp(np.log(x)) is not necessarily equal to x.',
  '    Notes',
  '           [1.,  1.]])',
  '    `allclose` is not defined for non-numeric data types.',
  '    a.sort(axis=axis, kind=kind, order=order, stable=stable)',
  '        as possible.',
  '        Input array.',
  'def base_repr(number, base=2, padding=0):',
  '             horizontally (column-wise).',
  '    newshape_b = (N2, math.prod([bs[ax] for ax in notin]))',
  '    ...     axis=-1).squeeze(axis=-1)',
  '    fromstring, inner, lexsort, matmul, may_share_memory, min_scalar_type,',
  '        else:',
  '    \'isclose\', \'isscalar\', \'binary_repr\', \'base_repr\', \'ones\',',
  '    """',
  '    and r/g/b channels (third axis). The functions `concatenate`, `stack` and',
  '            else:',
  '    a : array_like',
  '        iter(axes)',
  '        the first value in the output. With ``include_initial=True``',
  '    >>> np.correlate([1+1j, 2, 3-1j], [0, 1, 0.5j], \'full\')',
  '    >>> A.shape = (2, 2)',
  '    With a list of depth 2, `block` can be used in place of `vstack`:',
  '    and r/g/b channels (third axis). The functions `concatenate`, `stack` and',
  '    Graphical illustration:',
  '    array([[1.],',
  '    Parameters',
  '        fd.seek(0, 2)',
  '    Return the sum along diagonals of the array.',
  '    >>> x = [3, 4, 2, 1]',
  '    >>> np.compress([0, 1], a, axis=0)',
  '        Elements to compare for the maximum. See `~numpy.ufunc.reduce`',
  '        If `axis` is an int, the result is an array of dimension',
  '        return _atleast_nd(arrays, result_ndim)',
  '        with the dimension along `axis` removed. If `keepdims` is set to True,',
  'from . import numeric as _nx',
  '    The purpose is to allow easier editing of the docstrings without requiring',
  '    offset : int, optional',
  '    is only one position where they completely overlap:',
  '        otherwise.',
  '    array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])',
  '                axes_a[k] += nda',
  '        .. versionadded:: 2.1.0',
  '    a : array_like',
  '    # create local aliases for readability',
  '    This subclass of ndarray has some unpleasant interactions with',
  '        new_shape = (new_shape,)',
  '    array([[1, 2],',
  '# save away Python sum',
  '    def __repr__(self):',
  '             number of samples).',
  '        Specify the order of the ndarray memory layout:',
  '    axis : int, optional',
  '    array([ True, False])',
  '        detailed documentation.',
  '    than convolution, the function `scipy.signal.fftconvolve` exploits the',
  '            "Prefer to attach it directly to the source."',
  '           [5, 7]])',
  '    --------',
  '    dtype([((\'T1\', \'col1\'), \'<f8\'), ((\'T2\', \'col2\'), \'<i4\')])',
  '    ability to select the implementation and it is hardwired for the different',
  '    is no API to close the underlying ``mmap``. It is tricky to ensure the',
  '    >>> import numpy as np',
  '    --------',
  '        # We\'ve \'bottomed out\' - arrays is either a scalar or an array',
  '    Parameters',
  '          names=None, titles=None, aligned=False, byteorder=None, copy=True):',
  '    >>> np.fromfunction(lambda i, j: i, (2, 2), dtype=float)',
  '    array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])',
  '    ----------',
  '    same precision the input has.  Depending on the input data, this can',
  '        add_docstring(obj, doc)',
  '    Returns',
  '    See Also',
  '            # return a single element',
  '    Examples',
  '    def __repr__(self):',
  '        axes_a, axes_b = axes',
  '        # if not enough names are specified, they will be assigned as "f[n],',
  'import warnings',
  '    (2, 2, 3)',
  '    >>> np.min(a, axis=1)   # Minima along the second axis',
  '    ----------',
  '    return _wrapfunc(a, \'take\', indices, axis=axis, out=out, mode=mode)',
  '    >>> b = [(1, 1), (2, 4), (3, 9)]',
  '        # pretty-print all fields',
  '        >>> np.round(16.055, 2), round(16.055, 2)  # equals 16.0549999999999997',
  '    Given a memmap ``fp``, ``isinstance(fp, numpy.ndarray)`` returns',
  '    if dtype is not None:',
  'def _accumulate(values):',
  '    dimensions of the result. For example, if ``axis=0`` it will be the first',
  '    maximum :',
  '    pairwise summation) leading to improved precision in many use-cases.',
  '        Input array.',
  '    Examples',
  '    See also',
  '    >>> np.moveaxis(x, -1, 0).shape',
  '                return obj.view(dtype=(self.dtype.type, obj.dtype))',
  '        order in which they come up in the dtype, to break ties.',
  '        axis = -1',
  '        _nx.floor(y, out=y)',
  '    array([-2, -1,  0,  1,  2])',
  '    Parameters',
  '    (5, 4, 3, 2)',
  '        # 2018-02-07, 1.14.1',
  '    """',
  '    if na != nb:',
  '    This routine never raises an error if the docstring can\'t be written, but',
  '        be of the appropriate shape and dtype.',
  '    -----',
  '    # Turn all but python scalars into arrays.',
  '    The transpose of a C-ordered array is a FORTRAN-ordered array.',
  '            if issubclass(obj.dtype.type, nt.void):',
  '        When ``start <= axis``, the axis is rolled back until it lies in',
  '    not equal to one',
  'def _cumulative_func(x, func, axis, dtype, out, include_initial):',
  '              ...',
  '        | \'r+\' | Open existing file for reading and writing.                 |',
  '        By default, `dtype` is float.',
  'from ._ufunc_config import errstate',
  '    >>> x1 = np.array([1, 2, 3, 4])',
  '    >>> np.shape(np.eye(3))',
  '    def pprint(self):',
  '        Output array, with the same shape as `a`.',
  '    >>> plt.grid(True, color=\'0.7\', linestyle=\'-\', which=\'both\', axis=\'both\')',
  '            if _mult_inplace:',
  'umr_any = um.logical_or.reduce',
  '    .. note::',
  '    return pickle.dumps(self, protocol=protocol)',
  '    4.0',
  '    if type(a) is not mu.ndarray:',
  '    a1nan, a2nan = isnan(a1), isnan(a2)',
  '    False',
  '    -----',
  '    >>> np.ones(5)',
  '        --------',
  '    -----',
  '    out : ndarray',
  '    >>> ind',
  '        (e.g., if it is of type float, then it will remain so, returning',
  '        arguments. Either ``a_min`` and ``a_max`` or ``min`` and ``max``',
  '    a : array_like',
  '    >>> np.prod(a, axis=0)',
  '        The new shape should be compatible with the original shape. If',
  '        cp1 = cp[..., 1]',
  '    --------',
  '                        "argument: \'a_min\'")',
  '        cp2 = cp[..., 2]',
  '           [6]])',
  '        except AttributeError:',
  '    x : array_like',
  '        um.multiply(xv, xv, out=xv)',
  '    """',
  '        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is',
  '    >>> a',
  '           [3, 4]])',
  '                  \'<\': \'<\',',
  '            "`newshape` keyword argument is deprecated, "',
  '    array([[1]])',
  '        input array. If axis is negative it counts from the last to the',
  '    ----------',
  'def tensordot(a, b, axes=2):',
  '    mean, average',
  '        Alternative output array in which to place the result. It must',
  '    >>> b = a.copy()',
  '    Examples',
  '    return (condition, a, out)',
  '    Examples',
  '    >>> np.take_along_axis(x, np.expand_dims(index_array, axis=-1),',
  '    else:',
  '        Align the fields in memory as the C-compiler would.',
  '    True',
  '@array_function_dispatch(_cross_dispatcher)',
  '    ix_ : Construct index arrays.',
  '    -------',
  '    You can also start the sum with a value other than zero:',
  '    atleast_1d, atleast_2d',
  '        Returns True if the array is Fortran contiguous but *not* C contiguous.',
  '        array_like input, it will be treated as a sequence of arrays; i.e.,',
  '    -------',
  '        The elements of `a` are read using this index order. \'C\' means',
  '    >>> np.array(x)[np.argpartition(x, 3)]',
  '        Axis along which to sort. If None, the array is flattened before',
  '    array([False, False])',
  '    --------',
  '    >>> np.size(a)',
  'newaxis = None',
  '    in place of the true mean of the population. For this quantity, use',
  '        If this is set to True, the axes that are counted are left',
  '    result_ndim = max(arr_ndim, list_ndim)',
  '            # Special handling for denormal numbers, gh-5437',
  '    See Also',
  '    Parameters',
  '        Whether to compare NaN\'s as equal.  If True, NaN\'s in `a` will be',
  '    isclose, all, any, equal',
  '        they come up in the dtype, to break ties.',
  '    array([[[0, 1],',
  '    dtype : data-type, optional',
  '    # in place only for standard scalar types.',
  '    If `x` is of a signed integer type, then the output type',
  '        .. versionadded:: 1.24',
  '        return _block_slicing(arrays, list_ndim, result_ndim)',
  '    structured array:',
  '        the result will broadcast correctly against the input array.',
  '        memory, C-like order otherwise.  \'K\' means to read the',
  '    order : {\'C\',\'F\', \'A\', \'K\'}, optional',
  '    return (a,)',
  'def full(shape, fill_value, dtype=None, order=\'C\', *, device=None, like=None):',
  '    (0, 0)',
  '           [4, 5, 6],',
  '    axis1, axis2 : int, optional',
  '    else:',
  '    array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])',
  '    Returns',
  '        ``fp.tell() != 0``.',
  '        return super().__str__()',
  '    in a sorted array. In the output array, all elements smaller than the k-th',
  '        to True.',
  '    out : ndarray, optional',
  '    # version.',
  '    >>> np.block([a, b, 10])             # hstack([a, b, 10])',
  '        .. table::',
  '        When `a` is an array with fields defined, this argument specifies',
  '    """',
  '    .. warning:: The default `atol` is not appropriate for comparing numbers',
  '    >>> x = np.arange(10)',
  '        raise ValueError(',
  '        by the index that addresses the last element along that axis. Note',
  '        nn = descr[k].ndim',
  '    One dimensional array:',
  '    def __setattr__(self, attr, val):',
  '    >>> np.geomspace(-1+0j, 1+0j, num=5)  # Circle',
  '        The dimensionality of the output is equal to the greatest of:',
  '    Returns',
  '    1234',
  '    correction : {int, float}, optional',
  '    >>> import numpy as np',
  '           [3, 4, 5]])',
  '    except AttributeError:',
  '    F_order = all(arr.flags[\'F_CONTIGUOUS\'] for arr in arrays)',
  '    Returns the variance of the array elements, a measure of the spread of a',
  '"""',
  '    -------',
  '    >>> np.squeeze(x, axis=1).shape',
  '    if type(a) is not mu.ndarray:',
  '    \'all\', \'amax\', \'amin\', \'any\', \'argmax\',',
  '        \\sqrt{\\frac{\\sum_i{|a_i - \\bar{a}|^2 }}{N - 1}}',
  '    x = np.atleast_1d(x)',
  '            raise AttributeError("Cannot set \'%s\' attribute" % attr)',
  '        of shape ``(1, N, 1)``, and a 2-D array of shape ``(M, N)`` becomes a',
  '    >>> np.atleast_3d(3.0)',
  '    return a',
  '    """',
  'from ..exceptions import AxisError',
  '        # guarded to protect circular imports',
  '            lf = \' \' + lf  # trailing space',
  '        # sequences with 0 items or 1 item with endpoint=True (i.e. div <= 0)',
  '    Returns',
  '    elif isinstance(obj, recarray):',
  '                  & isfinite(y)',
  '        If True, `stop` is the last sample. Otherwise, it is not included.',
  '    >>> x.ravel()[np.flatnonzero(x)]',
  '    ndarray.resize : resize an array in-place.',
  '    a : array_like',
  '        If this is set to True, the axes which are reduced are left',
  '    --------',
  '    _array = recarray(shape, descr)',
  '    Returns',
  '    >>> np.cross(x, y)',
  '        Default is True.',
  '    array([[1, 2, 3, 4, 5],',
  '            [6, 7]]])',
  '        array of integers.',
  'def amax(a, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue,',
  'def swapaxes(a, axis1, axis2):',
  '    >>> np.repeat(x, [1, 2], axis=0)',
  '    a = moveaxis(a, axisa, -1)',
  '    >>> np.isfortran(b)',
  '    formats, names, titles, aligned, byteorder :',
  '            raise ValueError("Duplicate field names: %s" % _dup)',
  '    Since concatenation happens along the last axis first, `block` is *not*',
  '        na = 1',
  '    array([[0, 1, 2, 3]])',
  'def _swapaxes_dispatcher(a, axis1, axis2):',
  '    """Create a record array from a (flat) list of arrays',
  '    einsum : ``einsum(\'i,j->ij\', a.ravel(), b.ravel())`` is the equivalent.',
  '    -----',
  '    call. So ``np.block([[1, 2], [3, 4]])`` is equivalent to',
  '    --------',
  '    >>> a = np.ones((1, 2, 3))',
  '    dtype : dtype, optional',
  '    >>> a = np.array([1, 2, 3, 4])',
  '    Showing the shape equivalence:',
  '        return _block_concatenate(arrays, list_ndim, result_ndim)',
  '        the result will broadcast correctly against the input array.',
  '        "Delta Degrees of Freedom": the divisor used in the calculation is',
  '           [2, 2]])',
  '                formats=None, names=None, titles=None,',
  '            if shape is None:',
  '    destination = normalize_axis_tuple(destination, a.ndim, \'destination\')',
  '    Parameters',
  '    >>> x = [1, 2, 0]',
  '    Parameters',
  '        shape.',
  '    True',
  '    The sort order for complex numbers is lexicographic. If both the',
  '        except AttributeError:',
  '    >>> np.isclose([1e10,1e-7], [1.00001e10,1e-8])',
  '    # Check axisa and axisb are within bounds',
  '    destination : int or sequence of int',
  '    array([[4400., 4730.],',
  '    a : array_like',
  '        ``(\'x\', \'y\', \'z\')`` and `titles` is',
  '    all : ndarray, bool',
  '    will correctly handle 0-d arrays.',
  '    try:',
  '    interval [`start`, `stop`].',
  '    `amax` is an alias of `~numpy.max`.',
  '    >>> np.sum([])',
  '        if x_ndim >= 2:',
  '    >>> import numpy as np',
  '    >>> b[1] = 5',
  '    formats, names, titles, aligned, byteorder :',
  '    -------',
  '    ...               [-1, 127],',
  '        Fill value.',
  '    ----------',
  '        """Pretty-print all fields."""',
  '    >>> np.geomspace(1, 256, num=9)',
  '        Buffer (`buf`) is interpreted according to these strides (strides',
  '    >>> import numpy as np',
  '            pass',
  '        If True, then the newly created array will use the sub-class',
  '    In a two\'s-complement system negative numbers are represented by the two\'s',
  '        if argname:',
  '    ndarray.sort : Method to sort an array in-place.',
  '            [2, 4]],',
  '    shift : int or tuple of ints',
  '    >>> a.shape',
  '    ----------',
  '                          titles=titles, aligned=aligned, byteorder=byteorder)',
  '    array([4, 3])',
  '        `dtype` instead.',
  '        The number of dimensions in `a`.  Scalars are zero-dimensional.',
  '    >>> fp = np.memmap(filename, dtype=\'float32\', mode=\'w+\', shape=(3,4))',
  '    (2, 1, 3)',
  '    current size in the filesystem, the contents of the new part are',
  '        if out is not None:',
  '    dtype : data-type, optional',
  '@array_function_dispatch(_cumsum_dispatcher)',
  '           [0, 1, 2, 3]])',
  '    array([1., 1., 1., 1., 1.])',
  '            ret[(slice(None),) * axis + sl_a] == a',
  '    array([[4, 0, 1, 2, 3],',
  '                      stacklevel=2)',
  '    Return the maximum of an array or maximum along an axis.',
  '    return frombuffer(buf, dtype=dtype).reshape(shape, order=order)',
  '    Parameters',
  '    y : array_like',
  '        if shape is None:',
  '                return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)',
  '    False',
  '        The unstacked arrays.',
  '    >>> import numpy as np',
  '    >>> np.ptp(x)',
  '    Parameters',
  '    type(dtype(nt.int16)),',
  '    and imaginary parts are non-nan then the order is determined by the',
  '    --------',
  '    --------',
  '    Parameters',
  '    >>> id(z), id(o), z',
  '    stable : bool, optional',
  '        with f_ctx as fid:',
  '    default sort if none is chosen. For timsort details, refer to',
  '    [<matplotlib.lines.Line2D object at 0x...>]',
  '    res : ndarray',
  '    or padding (to increase the size) may be a more appropriate solution.',
  '        specified, in which case a reference to ``out`` is returned. The',
  '    Examples',
  '    The resulting array therefore has a value ``fn(x, y, z)`` at',
  '        The elements of the shape tuple give the lengths of the',
  '        The end value of the sequence, unless `endpoint` is set to False.',
  '    out : ndarray, optional',
  '    count_nonzero :',
  'and the Python code for the NumPy-namespace function',
  '    \'00012\'',
  '        AAAbb',
  '    >>> np.all([[True, True], [False, True]], where=[[True], [False]])',
  '       [a_1*b_0    .',
  '            descr = format_parser(',
  '    Not a Number (NaN), positive infinity and negative infinity evaluate',
  '                  \'>\': \'>\',',
  '    the converted data-type:',
  '    the last dimension (-1), then these are concatenated along the',
  'def _put_dispatcher(a, ind, v, mode=None):',
  '    the values. Furthermore, the default selection algorithm ``introselect``',
  '    >>> np.base_repr(10, base=16)',
  '    Examples',
  '                    "{}, but there is an element at depth {} ({})".format(',
  '    Notes',
  '    >>> # With thanks to Anne Archibald',
  '    overrides.array_function_dispatch, module=\'numpy\')',
  '        The starting value for this product. See `~numpy.ufunc.reduce`',
  '    higher-dimensional inputs are preserved.',
  '    >>> b = np.arange(6)',
  '    dt = dtype(descr)',
  '    Not a Number (NaN), positive infinity and negative infinity',
  '            shapeprod = sb.array(shape).prod(dtype=nt.intp)',
  '    array([[ 4.        ,  5.0396842 ,  6.34960421,  8.        ],',
  '        the returned array.',
  '           | ``-1``            | ``arr.ndim-1``       |',
  '            # matching rcount to arrmean when where is specified as array',
  '    order : {\'C\', \'F\', \'A\', or \'K\'}, optional',
  '    ------',
  '    return ufunc.reduce(obj, axis, bool, out, **passkwargs)',
  '            descr = sb.dtype(dtype)',
  '    the value of the element in k-th position is in the position it would be',
  '            pass',
  '    memmap([[  0.,   1.,   2.,   3.],',
  '        nt.dtype(nt.clongdouble) : nt.dtype(nt.longdouble),',
  '__all__ = [',
  '    in the `v` argument.',
  '            raise ValueError(',
  '      integer; negative integers are mapped to 0; values greater than ``n-1``',
  '        These are returned as tuples to ensure that they can quickly be added',
  '        compute the mean of the flattened array.',
  '    array([[-24,  48, -24],',
  '           +-------------------+----------------------+',
  '    Notes',
  '    Returns',
  '    --------',
  '    ... # the first element of the result will be the first element of the',
  '    nanmin, minimum, fmin',
  '    array([0., 2., 2., 4., 4.])',
  '        For further information, see `memmap`.',
  '        Note that `formats` must be a list, not a tuple.',
  '    >>> b = np.array([[4], [5], [6]])',
  '    # The fastest algorithm will depend on the ratio of CPU power to memory',
  '    See Also',
  '        Write any changes in the array to the file on disk.',
  '        Alternative output array in which to place the result. It must have',
  '    a : array_like',
  '    array([1., 2., 3.])',
  '        See `~numpy.ufunc.reduce` for details.',
  '    >>> import numpy as np',
  '    For performance, ``sort`` makes a temporary copy if needed to make the data',
  '    ndarray.size : number of elements in array',
  '    """',
  '        argument.',
  '    >>> fpc = np.memmap(filename, dtype=\'float32\', mode=\'c\', shape=(3,4))',
  '        The desired shape of the array. If ``mode == \'r\'`` and the number',
  '        if shape is None:',
  '    Return the binary representation of the input number as a string.',
  '               and base.',
  '    numpy.pad : Enlarge and pad an array.',
  '                return obj.view((self.__class__, obj.dtype))',
  '# The recarray is almost identical to a standard array (which supports',
  '        An array with the same shape as `a`, with the specified',
  '    # Test preferring F only in the case that all input arrays are F',
  '    ------',
  '    dtype : str or dtype',
  '    --------',
  '    >>> a.diagonal(0,  # Main diagonals of two arrays created by skipping',
  '            [0., 0., 0., 0.]], dtype=float32)',
  '    --------',
  '    See Also',
  '           [3, 4, 5],',
  '        The type of the output array.  If `dtype` is not given, the data type',
  '    >>> c.x',
  '        values will be cast if necessary.',
  '    """',
  '    """Construct an ndarray that allows field access using attributes.',
  '    precision the input has.  Depending on the input data, this can cause',
  '    hsplit : Split an array into multiple sub-arrays',
  '        a1, a2 = asarray(a1), asarray(a2)',
  'def _block_slicing(arrays, list_ndim, result_ndim):',
  '        interval in log-space, of which all but the last (a sequence of',
  '        try:',
  '        See :ref:`ufuncs-output-type` for more details.',
  '        return out',
  '        # First case must zero fill. The second would have repeats == 0.',
  '    res = []',
  '        ret = um.true_divide(',
  '    >>> a = np.array([[1,4],[3,1]])',
  '    dtype : dtype, optional',
  '        | \'r\'  | Open existing file for reading only.                        |',
  '    Returns',
  '    >>> a = np.array(0)',
  '    # TODO: this works around .astype(bool) not working properly (gh-9847)',
  '    than 1 become 1.',
  '        return asanyarray(a).ravel(order=order)',
  '        Axis along which the array will be split. Default: ``0``.',
  '        #  "f0, f1, f2,..."',
  '    --------',
  '    ndarray.shape : dimensions of array',
  '    initial : scalar, optional',
  '     array([[ 8,  9, 10, 11],',
  '    >>> a = np.array([1, 2, 3])',
  '        The file name or file object to be used as the array data buffer.',
  '    >>> a',
  '    ----------',
  '    copy : bool, optional',
  '        a if isinstance(a, (int, float, complex)) else asanyarray(a)',
  '    ndarray.flat : 1-D iterator over an array.',
  '            raise ValueError(',
  '    return _wrapreduction(a, np.minimum, \'min\', axis, None, out,',
  '        have the same shape and buffer length as the expected output',
  '        arrays, list_ndim, result_ndim)',
  '    >>> np.transpose(a, (-1, 0, -2)).shape',
  '    >>> x = np.arange(9.0).reshape(3,3)',
  '        if interface is None or not isinstance(interface, dict):',
  'def _size_dispatcher(a, axis=None):',
  '    if like is not None:',
  '    Examples',
  '            return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)',
  '        array must always be returned. If ``False`` and the specified dtype',
  '                for arr in arrays]',
  'def _roll_dispatcher(a, shift, axis=None):',
  '        The type of the returned array, as well as of the accumulator in',
  '    >>> x = np.array([(1.0, 2), (3.0, 4)], dtype=[(\'x\', \'<f8\'), (\'y\', \'<i8\')])',
  '    array([[0, 1, 2],',
  '        they come up in the dtype, to break ties.',
  '    mode : str',
  '    See Also',
  '    array([[1, 3],',
  '    array([[-3,  6, -3],',
  '    if axis is None:',
  '        Specifies how indices outside ``[0, n-1]`` will be treated:',
  '           [1, 3]])',
  '            ``grid[i].shape = (1, ..., 1, dimensions[i], 1, ..., 1)`` with',
  '    ----------',
  '    array([1, 2, 6])',
  '        step = delta / div',
  '    ...     print(arr, arr.shape) # doctest: +SKIP',
  '        formats. Use list of tuples rather than list of lists for faster',
  '        .. versionadded:: 1.20.0',
  '        the coordinate arrays passed to `function`.',
  '           [0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j, 0.-1.j],',
  '        the relative order of ``a`` values which compare as equal.',
  '    where : array_like of bool, optional',
  '        See Also',
  '    Supports full broadcasting of the inputs.',
  '        `order`, and packed as a 1-D array.',
  '    >>> z=np.any([-1, 4, 5], out=o)',
  '    >>> c1 = np.array([1, 2, 3]).reshape((1,3,1))',
  '    rcount = um.maximum(rcount - ddof, 0)',
  '        .. versionadded:: 2.0.0',
  'from . import _methods',
  '    -------- ',
  '            if dt.names is not None:',
  '    """',
  '    axis : int or tuple of ints, optional',
  'extend_all(arrayprint)',
  '        an integer; `float` is chosen even if the arguments would produce an',
  '    >>> x2 = np.logspace(0.1, 1, N, endpoint=False)',
  '    axis : int, optional',
  '        return builtins.bool((asanyarray(a1 == a2)).all())',
  '    nor \'F\', but won\'t reverse axes:',
  '    array([0., 2.])',
  '    >>> x = np.arange(6)',
  '    return (x,)',
  '    """',
  '            \'formats\': self._f_formats,',
  '        Axis or axes along which a product is performed.  The default,',
  '    -------',
  '    """',
  '        data in the same field may be heterogeneous - they will be promoted',
  '        broadcasting), but leading 1s will be prepended to the shape as',
  '    Returns the indices of the maximum values along an axis.',
  '        The axis in the result to store the samples.  Relevant only if start',
  '            self.base.flush()',
  '    array([ 126,  127, -128, -127], dtype=int8)',
  '    -------',
  '    ``max(a, axis=0)``.',
  '        try:',
  '    Assuming the input `a` is a one-dimensional NumPy array and ``mean`` is',
  '    Notice that this isn\'t the same as Python\'s ``default`` argument.',
  '        If this is a tuple of ints, a variance is performed over multiple axes,',
  '    return items',
  '        which case it counts from the last to the first axis.',
  '    Examples',
  '        shape as ``a.shape``.',
  '        reversing the data when strides are negative.  By default, \'C\'',
  'import warnings',
  '    equal_nan : bool',
  '        try:',
  'def _astype_dispatcher(x, dtype, /, *, copy=None, device=None):',
  '    axis : int, optional',
  'import os',
  '    ------',
  '    +------------------------------------+---------------+-------------------+',
  '    except AttributeError:',
  '    """',
  '        The axis for the calculation of the mean should be the same as used in',
  '@array_function_dispatch(_rollaxis_dispatcher)',
  '            _, (sl_a, sl_b, sl_c) = concatenate_slices([a, b, c], axis)',
  'import types',
  '        be of the same shape and buffer length as the expected output.',
  '        that case, the default platform integer is used.',
  '        Input array.',
  '    -------',
  '    >>> x = np.arange(12.0).reshape(4,3)',
  '    Multiple vector cross-products. Note that the direction of the cross',
  '    >>>',
  '    allclose',
  '    NaN values are propagated, that is if at least one item is NaN, the',
  '    in Python 3.x) of Python objects that tests an object\'s',
  '            fmt = \'rec.array(%s,%sdtype=%s)\'',
  '    order : {\'C\', \'F\', \'A\', or \'K\'}, optional',
  '    >>> np.array_equiv([1, 2], [[1, 2, 1, 2], [1, 2, 1, 2]])',
  '        result = a.shape',
  '           [0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j, 0.+1.j],',
  '    --------',
  '    See Also',
  '        # axis=None (note that subclasses will not reach here)',
  '        obj = super().__getitem__(indx)',
  '    base : array_like, optional',
  '    Starting in NumPy 1.9 it returns a read-only view on the original array.',
  '    >>> np.isclose([1e-100, 1e-7], [0.0, 0.0], atol=0.0)',
  '    ``p2[8]``, and all elements in ``p2[9:]`` are greater than or',
  '    ``cumulative_sum(c)[-1]`` may not be equal to ``sum(c)``',
  '    a, b : array_like',
  '    return type(dtype) in _no_nan_types',
  '    --------',
  '    >>> np.isscalar(Fraction(5, 17))',
  '    :ref:`ufuncs-output-type`',
  '    >>> import numpy as np',
  '    This function is equivalent to ``tuple(np.moveaxis(x, axis, 0))``, since',
  '    >>> np.geomspace(1, 1000, num=4)',
  '        If this is set to True, the axes which are reduced are left',
  'def array_equiv(a1, a2):',
  '    >>> np.max(a, axis=0)   # Maxima along the first axis',
  '        If file is a string or a path-like object then that file is opened,',
  '    Join a sequence of arrays along a new axis.',
  '    if isinstance(a, np.matrix):',
  '        Array of insertion points with the same shape as `v`,',
  '        This will be a new view object if possible; otherwise, it will',
  '    """',
  '    return _wrapreduction(',
  '    True',
  '    return function(*args, **kwargs)',
  '    See Also',
  '    elif isinstance(doc, list):',
  '    array([[1, 3],',
  '    a, fill_value, dtype=None, order=None, subok=None, shape=None,',
  '    >>> ((1-0.55)**2 + (0.1-0.55)**2)/2',
  '            [  4.,   5.,   6.,   7.],',
  '            if 2**(poswidth - 1) == -num:',
  '    --------',
  '    the index along the last quickest.  The opposite holds for',
  '    endpoint : bool, optional',
  '        # TODO: Optimize case when `where` is broadcast along a non-reduction',
  '        By default `ddof` is zero. See Notes for details about use of `ddof`.',
  'def _convolve_dispatcher(a, v, mode=None):',
  '        else:',
  '            "the python sum builtin instead.",',
  '        or an integer if `v` is a scalar.',
  '    `b` has magnitude smaller than one. For example, it is unlikely that',
  'import os',
  '        # A TypeError occurs if the object does have such a method in its',
  '                # gh-27723',
  '    --------',
  '    # It didn\'t seem to matter heavily on the dtype used.',
  'array_function_dispatch = functools.partial(',
  '    memmap([[  0.,   0.,   0.,   0.],',
  '    Timsort is added for better performance on already or nearly',
  '    --------',
  '    \'fromiter\', \'array_equal\', \'array_equiv\', \'indices\', \'fromfunction\',',
  '    >>> a',
  '    >>> a.diagonal()',
  '    """',
  '        for ax in axis:',
  '        * ``axes = 2`` : (default) tensor double contraction :math:`a:b`',
  '    """',
  '    array([[1, 2],',
  '    axes.insert(start, axis)',
  '        exceptions will be raised.',
  '            elif isinstance(names, str):',
  '    -------',
  '    >>> np.take_along_axis(x, ind, axis=1)  # same as np.sort(x, axis=1)',
  '    Parameters',
  '    kwds = {\'keepdims\': keepdims} if keepdims is not np._NoValue else {}',
  '    concatenate : Join a sequence of arrays along an existing axis.',
  '    Counts the number of non-zero values in the array ``a``.',
  '    >>> np.array_equal([1, 2], [1, 2, 3])',
  '    try:',
  '    ----------',
  '        Return a sparse representation of the grid instead of a dense',
  '        Alternative output array in which to place the result.  Must',
  '        record array consisting of data enclosed in file.',
  '                    try:',
  '        \'C\' otherwise. \'K\' means match the layout of `a` as closely',
  '        Input argument, can be of any type and shape.',
  'def unstack(x, /, *, axis=0):',
  '        is inferred from `start` and `stop`. The inferred dtype will never be',
  '                size = np.intp(1)  # avoid default choice of np.int_, which might overflow',
  '    """',
  '    Return an array of zeros with the same shape and type as a given array.',
  '        return parent_index + [None], 0, 0',
  '    """',
  '        ``[\'i4\', \'f8\', \'i4\']``.  `formats` does *not* support the new',
  '    >>> x = np.arange(6)',
  '        return self',
  '    if a.size == 0 or new_size == 0:',
  '        start, stop, base = (',
  '    if list_ndim * final_size > (2 * 512 * 512):',
  '    >>> b',
  '         ``np.array(fill_value).dtype``.',
  '        in the result as dimensions with size one. With this option,',
  '    array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ])',
  '        is a tuple of ints, a reduction is performed on multiple',
  '    if depth < max_depth:',
  '        return val',
  '        Axis along which the cumulative sum is computed. The default',
  '    (10,)',
  '    -------',
  '             [14, 16]]],',
  '    res : ndarray',
  '    \'11101\'',
  '    individually to the result causing rounding errors in every step.',
  '    array([[ 1,  2,  3],',
  '    a = empty(shape, dtype, order, device=device)',
  '            Passing booleans as index is deprecated.',
  'import functools',
  '    return ``obj.view(recarray)``, making a copy of the data if ``copy=True``.',
  '        Alternative output array in which to place the result. It must have',
  '        the shape of the output is different than the shape of the input.',
  '    >>> np.prod(x)',
  '    min : ndarray or scalar',
  '                if flen < bytes:',
  '    Supports rolling over multiple dimensions simultaneously.',
  '    relative order. The available algorithms have the following',
  '    Examples',
  '    >>> result = np.searchsorted(a, 25, sorter=sorter)',
  '                    initial=None, where=None):',
  '    out : ndarray, optional',
  '    # By default, return a boolean for any and all',
  '    Parameters',
  '            arrmean = arrmean.dtype.type(arrmean / rcount)',
  '        result = asarray(a).shape',
  '    axes : tuple or list of ints, optional',
  '    >>> a = np.array([[14, 8, 11, 10], [7, 9, 10, 11], [10, 15, 5, 10]])',
  '    --------',
  '        axes as before.',
  '           [0, 1, 2, 3, 4]])',
  '    Parameters',
  '    >>>',
  'def transpose(a, axes=None):',
  '    yields the indices of the `a` where the condition is true.',
  '            shape == concatenate(arrs, axis).shape',
  'import itertools',
  '    .. math::',
  '                  \'L\': \'<\',',
  'from .multiarray import array, asanyarray, normalize_axis_index',
  '    # Move working axis to the end of the shape',
  '        elif not isinstance(axis, tuple):',
  'def _reshape_dispatcher(a, /, shape=None, order=None, *, newshape=None,',
  '           [1, 1, 2, 2]])',
  '    >>> filename = path.join(mkdtemp(), \'newfile.dat\')',
  '    Notes',
  '    inner : Inner product',
  '@array_function_dispatch(_std_dispatcher)',
  '    C-ordered arrays evaluate as False even if they are also FORTRAN-ordered.',
  '        # \'pandas\'.',
  '    Return the number of elements along a given axis.',
  '    >>> x = np.array([[4, 9, 2, 10],',
  '    array([0.   +1.j, 0.  +10.j, 0. +100.j, 0.+1000.j])',
  '    `a` as if `a` were a complete population of possible observations.',
  '    equivalent to ``np.block([[A, B, ...], [p, q, ...]])``.',
  '                    except TypeError:',
  '    if any(shape[:axis] != first_shape_pre or',
  '    abc',
  '        all given axes.',
  '    dtype : dtype',
  '    stop : array_like',
  '            shifts[ax] += int(sh)',
  '            ret = object.__setattr__(self, attr, val)',
  '    for i, dim in enumerate(dimensions):',
  '            self.offset = obj.offset',
  '    selects elements.',
  '    with a and v sequences being zero-padded where necessary and',
  '    array([[3, 4]])',
  '    Arithmetic is modular when using integer types, and no error is',
  '        The device on which to place the created array. Default: None.',
  '        shape = _deprecate_shape_0_as_None(shape)',
  '    >>> a = np.array([[1,2,3], [4,5,6]])',
  '        d2 = abs(a - mean)**2  # abs is for complex `a`',
  '    The product of an empty array is the neutral element 1:',
  '    >>> a = np.array([1 + 1j])',
  '    copy : bool, optional',
  '    This is equivalent to concatenation along the second axis, except for 1-D',
  '        in the result as dimensions with size one. With this option,',
  '    >>> N = 8',
  '    >>>',
  '        shape, slice_prefixes = _concatenate_shapes(shapes, axis)',
  '    Returns',
  '    ndarray.argmax, argmin',
  '    width : int, optional',
  '        raise ValueError("shape-mismatch for sum")',
  '    new array using the same kind of index ordering as was used for the',
  '    """Find duplication in a list, return a list of duplicated elements"""',
  '    >>> a = np.zeros((2, 512*512), dtype=np.float32)',
  '            cp1 -= tmp',
  '    Other axes remain in their original order.',
  '    # that fails the reloading test.',
  '    >>> np.reshape(a, (2, 3)) # C-like index ordering',
  '    The next example shows the use of multiple values passed to `kth`.',
  '    Returns True if two arrays are element-wise equal within a tolerance.',
  '        to True.',
  '        If this is set to True, the axes which are reduced are left',
  '    return result',
  '    array([0, 0, 0, 0, 0, 0])',
  '    """',
  '        if _get_legacy_print_mode() <= 113:',
  '        Elements to include in checking for all `True` values.',
  '        If `buf` is specified and is an object exposing the buffer interface,',
  '    """',
  '    --------',
  '        dtype = fill_value.dtype',
  '    array([1, 2, 3], dtype=int16)',
  '    >>> np.prod(a)',
  '        return False',
  '    --------',
  '                  \'I\': \'|\',',
  '        In that case, the default platform integer is used.',
  '    array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.])',
  'def _concatenate_shapes(shapes, axis):',
  '    RAISE, WRAP, arange, array, asarray, asanyarray, ascontiguousarray,',
  '    >>> np.any([[True, False], [True, True]])',
  '    """',
  '    partitioning along any other axis.',
  '    if axis is None and not keepdims:',
  '    """',
  '    See Also',
  '            shape = tuple(shape)',
  '    ----------',
  '    --------',
  '        array for in-place clipping.  `out` must be of the right shape',
  '    False',
  '    >>> np.transpose(a, (1, 0, 2)).shape',
  '            result = ary',
  '    relative difference (`rtol` * abs(`b`)) and the absolute difference',
  '    numpy.take_along_axis : Preferable if `choices` is an array',
  '    >>> import matplotlib.pyplot as plt',
  '                "at the same time.")',
  '        # f[n+1],..." etc. where n is the number of specified names..."',
  '    else:',
  '        The slices into the full array required for assignment. These are',
  '    Gives a new shape to an array without changing its data.',
  '    complement of the absolute value. This is the most common method of',
  '    array is filled with repeated copies of `a`.  Note that this behavior',
  '    The sum of an empty array is the neutral element 0:',
  '        the result will broadcast correctly against the array.',
  '    memory (first index varies the fastest).',
  '    True',
  '        actual implementation will vary with data type. The \'mergesort\' option',
  'def moveaxis(a, source, destination):',
  '    ndarray.compress : Equivalent method in ndarray',
  '    these attributes are accessed using dictionary lookups such as ``arr[\'x\']``',
  '    arr = asanyarray(a)',
  '    return (a, where, out)',
  '    - modifying a `PyTypeObject` after calling `PyType_Ready`',
  '        array, a conversion is attempted.',
  '@array_function_dispatch(_diagonal_dispatcher)',
  '        ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``',
  '    fromfunction : any',
  '        processing.',
  '        else:',
  '        is retained for backwards compatibility.',
  '    res, res2, ... : ndarray',
  '            [ 4,  5,  6,  7],',
  '    >>> x = np.array([[[0], [1], [2]]])',
  '    >>> b = np.arange(5, dtype=float)',
  '        # with void type convert it to the same dtype.type (eg to preserve',
  '    array([12, -6, -3])',
  '    The ``order`` keyword gives the index ordering both for *fetching*',
  '    4.0',
  '    ...                      [\'T1\', \'T2\']).dtype',
  '        By default, a new array is created of the given shape and data-type.',
  '    2.5',
  '    >>> t1 = timeit("std = np.std(a, axis=1, mean=mean)", globals=g, number=n)',
  '    overrides.array_function_dispatch, module=\'numpy\')',
  '           [[ 6,  8, 10],',
  '    Parameters',
  '            multiply(a1, b0, out=tmp)',
  '# Special case for windows: ensure double takes precedence',
  '        if self._nfields > len(titles):',
  '            raise ValueError(',
  '    np.int8(-128)',
  '    \'quicksort\'    1     O(n^2)            0          no',
  '    else:',
  '    --------',
  'def _max_dispatcher(a, axis=None, out=None, keepdims=None, initial=None,',
  '    vstack : Stack arrays in sequence vertically (row wise).',
  'False_ = nt.bool(False)',
  '           [4, 5, 6]])',
  '    arrays = _arrays_for_stack_dispatcher(arrays)',
  '        support random access (i.e. it must have tell and seek methods).',
  '    >>> np.vstack((a,b))',
  '        Array with moved axes. This array is a view of the input array.',
  '    Parameters',
  '    Examples',
  '    return _wrapfunc(a, \'cumprod\', axis=axis, dtype=dtype, out=out)',
  '        equal = False',
  '        If True, then the newly created array will use the sub-class',
  '        y = float(y)',
  '        See :ref:`ufuncs-output-type` for more details.',
  '    >>> a = np.ones((2, 3, 4, 5))',
  '    >>> x1[1]=34',
  '    ``a = 1e-9`` and ``b = 2e-9`` should be considered "close", yet',
  '    Parameters',
  '        The source array.',
  '          illegal, and should be spelt ``[[a, b], [c]]``',
  '    """',
  '_ndim = getattr(_from_nx.ndim, \'__wrapped__\', _from_nx.ndim)',
  '    scipy.signal.correlate : uses FFT which has superior performance',
  '    \'stable\' automatically chooses the best stable sorting algorithm',
  '    multiarray.copyto(res, z, casting=\'unsafe\')',
  '    demanding algorithm to compute the number of digits after the decimal',
  '    num = abs(int(number))',
  '                        shape = [operator.index(shape)]',
  '            final_size += size',
  '    -------',
  '        x = um.multiply(x, x, out=x)',
  '    a : array_like',
  '        (C-style) or column-major (Fortran-style) order in',
  '    >>> a.diagonal(1)',
  '    (see `endpoint` below).',
  '             [28, 32]]]])',
  '    """',
  '        Type of the returned array, as well as of the accumulator in which',
  '    | the result of `re.compile`         |               |                   |',
  '        If provided, the destination to place the result. The shape must be',
  '        while `axis` is a tuple of ints, then the same value is used for',
  '    if len(arys) == 1:',
  '    """',
  '    built-in method ``__nonzero__()`` (renamed ``__bool__()``',
  '        memory.',
  '        `arrays`. If any element at the bottom is an empty list, this will',
  '        y = y * delta',
  '            assert b.shape[-1] == 2',
  'def cumulative_prod(x, /, *, axis=None, dtype=None, out=None,',
  '    corresponding min value will be NaN as well. To ignore NaN values',
  '    ``np.block([[a, b], [c, d]])`` is not restricted to arrays of the form::',
  '@array_function_dispatch(_any_dispatcher)',
  '    else:',
  'def argpartition(a, kth, axis=-1, kind=\'introselect\', order=None):',
  '        for more details.',
  '    >>> fp[:] = data[:]',
  '        For Array-API interoperability only, so must be ``"cpu"`` if passed.',
  '            "give a different result. Use np.sum(np.fromiter(generator)) or "',
  '    If the inputs or dtype are complex, the output will follow a logarithmic',
  '    # manually set name and module so that this class\'s type shows up',
  '        raise ValueError(\'`source` and `destination` arguments must have \'',
  '    array([[0, 1, 2],',
  '    >>> np.array_equal(a, a)',
  '    else:',
  '    1.0',
  '    --------',
  '    1. Create a standard ndarray and convert it to a record array,',
  '    Notes',
  '    np.float64(nan)',
  '    np.recarray',
  '    r"""',
  '    >>> np.shape([[1, 3]])',
  '    if axis is None:',
  'def hstack(tup, *, dtype=None, casting="same_kind"):',
  '        Alternate output array in which to place the result.',
  '                          keepdims=keepdims, initial=initial, where=where)',
  '    Returns',
  '    files to your directory. You would use a \'normal\' filename.',
  '            Returns one array of grid indices,',
  '        # numpy.record type if present), since nested structured fields do not',
  '    >>> data.resize((3,4))',
  '    """',
  '    axis = normalize_axis_index(axis, n)',
  'def take(a, indices, axis=None, out=None, mode=\'raise\'):',
  '    -------',
  '        slowest. Note that the \'C\' and \'F\' options take no account of',
  '    elif isinstance(shape, int):',
  '    2.0',
  '        new axis inserted at the beginning. Use -1 to get an axis at the end.',
  '            if newattr:',
  '            names = ndarray.__getattribute__(self, \'dtype\').names',
  '    (5, 3, 4, 6)',
  '    stop = stop / out_sign',
  '    more precise approach to summation.',
  '    def __array_finalize__(self, obj):',
  '    >>> b = a.T',
  '    See Also',
  '        out',
  '    correlation may be defined differently. Another common definition is [1]_:',
  '    shape, fill_value, dtype=None, order=None, *, device=None, like=None',
  '    casting : {\'no\', \'equiv\', \'safe\', \'same_kind\', \'unsafe\'}, optional',
  '    of `apply_along_axis`::',
  '    Examples',
  '        return value for an input of signed integers with n bits',
  'def clip(a, a_min=np._NoValue, a_max=np._NoValue, out=None, *,',
  '        The converted data-type.',
  '          initial=_NoValue, where=True):',
  '    if isinstance(a, _gentype):',
  '    max : ndarray or scalar',
  '@array_function_dispatch(_array_equal_dispatcher)',
  '    >>> x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])',
  '        Axis or axes along which the means are computed. The default is to',
  '@set_module("numpy.rec")',
  '        NumPy versions a view of `a` is returned only if the order of the',
  '        axes_a = [axes_a]',
  '        specified, in which case a reference to out is returned.',
  '    \'flatnonzero\', \'inf\', \'nan\', \'False_\', \'True_\', \'bitwise_not\',',
  '    ----------',
  '            FutureWarning, stacklevel=2)',
  '        axes specified in the tuple instead of a single axis or all the',
  '    Parameters',
  '         where=True, mean=None):',
  '           [1, 2]])',
  '        have the same shape and buffer length as the expected output',
  '        ``a.ndim - 1``. If `axis` is a tuple, the result is an array of',
  '    .. versionchanged:: 2.0',
  '                        "argument: \'a_max\'")',
  '    array([[0, 2],',
  '        (depending on whether `endpoint` is True or False).',
  '        with shape ``(a.size,)``.',
  '@array_function_dispatch(_min_dispatcher)',
  '    >>> x = np.array([[0, 3], [2, 2]])',
  '    (-0.5, 1)',
  '    bt = b.transpose(newaxes_b).reshape(newshape_b)',
  '            UserWarning,',
  '# Complex types to -> (2,)float view for fast-path computation in _var()',
  '    Returns',
  '    dtype : data-type, optional',
  '        Axis along which to take slices. If None (default), work on the',
  '             endpoint may or may not be included.',
  '        Input data.',
  '    This function is an Array API compatible alternative to `numpy.cumsum`.',
  '    >>> x2 = np.linspace(0, 10, N, endpoint=False)',
  '            # cp0 = a1 * b2 - 0  (a2 = 0)',
  '           formats is None and dtype is None):',
  '           [ True,  True],',
  '            dimensions[i] in the ith place',
  '    >>> np.cumulative_sum(b,axis=0)  # sum over rows for each of the 3 columns',
  '    partition : Partial sort.',
  '    shape: tuple of int',
  '    be generalized to multiple dimensions, where row-major order',
  '        Alternative output array in which to place the result. It must',
  '    >>> a = np.arange(10)',
  '    error due to the inexact representation of decimal fractions in the IEEE',
  '            attr == \'dtype\' and',
  '         where=np._NoValue):',
  '        Specifies how out-of-bounds indices will behave.',
  '    # Most general case; includes handling object arrays containing imaginary',
  '    Class to convert formats, names, titles description to a dtype.',
  '    Returns',
  '    >>> b = np.array([[1, 2, 3], [4, 5, 6]])',
  '    """',
  '    put_along_axis : Put elements by matching the array and the index arrays',
  '        For NumPy >= 1.10.0 a view of `a` is always returned. For earlier',
  '    ``cumsum(b)[-1]`` may not be equal to ``sum(b)``',
  '    if a.dtype.kind in "iu":',
  '        if return_scalar:',
  '        res = [_maketup(fields[name][0], val) for name in dt.names]',
  '    "readwrite":"r+",',
  '    Negative, decreasing, and complex inputs are allowed:',
  '    .. math:: c\'_k = \\sum_n a_{n} \\cdot \\overline{v_{n+k}}',
  '       is actually used, even if \'mergesort\' is specified. User selection',
  '        |      | If ``mode == \'w+\'`` then `shape` must also be specified.    |',
  '    Parameters',
  '    axis : int, optional',
  '    1000000.0050000029',
  '    array([1, 1, 2, 1])',
  '        Input data.',
  '    a, dtype=None, order=None, subok=None, shape=None, *, device=None',
  '@array_function_dispatch(_cumprod_dispatcher)',
  '        of integer type of precision less than the default integer',
  '    """',
  '    >>> np.any([[True,  False, True ],',
  '    else:',
  '    return (a,)',
  '    kind : {\'quicksort\', \'mergesort\', \'heapsort\', \'stable\'}, optional',
  '# Use getattr to protect against __array_function__ being disabled.',
  '    p : ndarray',
  '        where=np._NoValue, mean=np._NoValue, correction=np._NoValue):',
  '    .. [1] Wikipedia, "Cross-correlation",',
  '        raise ValueError(',
  '        def cross2d(x, y):',
  '            poswidth = len(bin(-num)[2:])',
  'extend_all(fromnumeric)',
  '        \'clip\' mode means that all indices that are too large are replaced',
  '    return (a,)',
  '    Examples',
  '    >>> arrays = [rng.normal(size=(3,4)) for _ in range(10)]',
  '    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])',
  '        from `formats`, `names`, `titles`, `aligned` and `byteorder`.',
  '    """',
  '    keepdims : bool, optional',
  '    nan values. The enhanced sort order is documented in `sort`.',
  '    Normalizes an axis argument into a tuple of non-negative integer axes.',
  '        If a string, the documentation to apply to `obj`',
  '    >>>',
  '    View the array as a record array:',
  '    memmap([  4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.], dtype=float32)',
  '    This is equivalent to concatenation along the first axis after 1-D arrays',
  '    >>> np.isscalar(False)',
  '    clipped_array : ndarray',
  '            result = result.reshape(1)',
  '    (5, 2)',
  '    >>> np.rec.format_parser([\'<f8\', \'<i4\'], [\'col1\', \'col2\'],',
  '    device : str, optional',
  '        as possible.',
  '        `ndarray`, however any non-default value will be.  If the',
  '    # around 256x256 was faster by straight concatenation on a',
  '    if a.shape[-1] == 2:',
  '    shape : int or sequence of ints, optional.',
  '        The minimum value of an output element. Must be present to allow',
  '    """',
  '    returned, with respect to that width.',
  '           [3]])',
  '    >>> np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)',
  '    Examples',
  '        .. versionadded:: 2.0.0',
  '        pass',
  '    Using this result to index `a` is equivalent to using the mask directly:',
  '    \'11\'',
  '    --------',
  '    (28293632, 28293632, array(True)) # may vary',
  '    # (e.g., for numpy.ma).',
  '    \'introselect\'        1        O(n)           0         no',
  '    array([[0, 1, 2],',
  '    Technically, to provide the best speed possible, the improved precision',
  '        diagonal.',
  '           | ``0``             | ``0``                |',
  '    Return a partitioned copy of an array.',
  '    --------',
  '    \'ndim\', \'nonzero\', \'partition\', \'prod\', \'ptp\', \'put\',',
  '    either provided as an argument or computed as ``a.mean()``, NumPy',
  '    This class may at some point be turned into a factory function',
  'umr_minimum = um.minimum.reduce',
  '@set_module(\'numpy\')',
  '    array([[2],',
  '    >>> np.cumsum(a, dtype=float)     # specifies type of output value(s)',
  '    yield a',
  '@array_function_dispatch(_sum_dispatcher)',
  '        specified, in which case a reference to `out` is returned. The',
  '    # not a scalar.',
  '    array([  1.,   3.,   6.,  10.,  15.,  21.])',
  '    arr = asanyarray(a)',
  '    >>> np.block([[b]])                  # atleast_2d(b)',
  '    if like is not None:',
  '        dimensions form ``MxN`` matrices.',
  '            obj = self.getfield(*res)',
  '    dtype : dtype, optional',
  'mode_equivalents = {',
  '        if ary.ndim == 0:',
  '    instance, for pixel-data with a height (first axis), width (second axis),',
  '    Examples',
  '            # cp2 = a0 * b1 - a1 * b0',
  '        dt = multiarray.result_type(y, 1.)',
  '           [2, 5],',
  '    array([2, 1, 0])',
  '            return nt.void.__getattribute__(self, attr)',
  '        When `a` is an array with fields defined, this argument specifies',
  '    """',
  '        can be passed at the same time. Default: ``None``.',
  '    ``allclose(1e-9, 2e-9)`` is ``True`` with default settings. Be sure',
  '    (``side=\'right\'``) functions, which is also vectorized',
  '            raise ValueError("For arrays which have more than one dimension "',
  '    """',
  '    Setting `keepdims` to `True`,',
  '    Returns',
  '        if copy:',
  '    array(1234)  # 0d array',
  '        provided together with `out`.',
  '        # open file',
  'def fromrecords(recList, dtype=None, shape=None, formats=None, names=None,',
  '        `num` samples, equally spaced on a log scale.',
  '    the index of the offending list can be printed as part of the error.',
  '        Given that `formats` is somewhat limited, we recommend specifying',
  '    --------',
  '    array([[1.,  1.],',
  'def argmax(a, axis=None, out=None, *, keepdims=np._NoValue):',
  '    >>> import numpy as np',
  'from numpy._core import numerictypes as nt',
  '    keepdims : bool, optional',
  '    rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)',
  '        instead of a single axis or all the axes as before.',
  '        A new array holding the result is returned unless ``out`` is',
  '    circular convolution).  Since multiplication is more efficient (faster)',
  '    -----',
  '    >>> np.correlate([0, 1, 0.5j], [1+1j, 2, 3-1j], \'full\')',
  '    --------',
  '    speed, worst case performance, work space size, and whether they are',
  '    ``k-th`` axis. Explicitly::',
  '        return self.setfield(val, *res)',
  '    array([[0, 0, 0],',
  '        ``base ** start`` is the starting value of the sequence.',
  '        for k in range(_array.size):',
  '            res = res + (idx,)',
  '    See Also',
  '    the values from ``a``, and then *placing* the values into the output',
  '    partition : Describes partition algorithms used.',
  'def get_remaining_size(fd):',
  '        True if equivalent, False otherwise.',
  '        # list of lists instead of list of tuples ?',
  '        When the dimension of the vector(s) in `a` and/or `b` does not',
  '    a0 = a[..., 0]',
  '    a : array_like',
  '        of `obj` and the second as the docstring to apply -',
  '    return builtins.bool((a1[~a1nan] == a2[~a1nan]).all())',
  '    if x.ndim == 0:',
  '    axis : int, optional',
  '    >>> s = \'\\x01\\x02\\x03abc\'',
  'This module contains a set of functions for record arrays.',
  '    Add documentation to an existing object, typically one defined in C',
  '    if dtype is None:',
  '    >>> import numpy as np',
  '    a = asanyarray(a)',
  '    When there is more than one axis to sum over - and they are not the last',
  '    tolerance.',
  '    to columns in a spread sheet.  An example is ``[(x, int), (y, float)]``,',
  '        a precision less than that of the default platform integer.',
  '@array_function_dispatch(_trace_dispatcher)',
  '            "3-dimensional vectors instead. (deprecated in NumPy 2.0)",',
  '    names : str or list/tuple of str',
  '    """',
  '    expanded_arrays = [arr[sl] for arr in arrays]',
  '        |      | read-only.                                                  |',
  '    --------',
  '           [3]])',
  '    Return the number of dimensions of an array.',
  '    byteorder : {\'<\', \'>\', \'=\'}, optional',
  '        exceptions will be raised.',
  '    minimum :',
  '        return False',
  '    where R is a non-nan real value. Complex values with the same nan',
  '    a : array_like',
  '    a : array_like',
  '    # Undo any "setting" of the attribute and do a setfield',
  '    return umr_any(a, axis, dtype, out, keepdims, where=where)',
  '    distributed according to the convolution of their individual',
  '        result has the same size as `a`, and the same shape as `a` if',
  'def _array_equal_dispatcher(a1, a2, equal_nan=None):',
  '@array_function_dispatch(_var_dispatcher)',
  '    shapes = {arr.shape for arr in arrays}',
  '    if dtype is None and formats is None:',
  '        if dtype is not None and (obj.dtype != dtype):',
  '        This array must contain integers in ``[0, n-1]``, where ``n`` is the',
  '    a = empty(shape, dtype, order, device=device)',
  '        final sorted position and all smaller elements will be moved',
  '    max : alias of this function',
  '    True',
  '    >>> a = np.arange(4).reshape((2,2))',
  '        this option selects ``kind=\'stable\'``. Default: ``None``.',
  '                # py3 returns int for TemporaryFile().name',
  '        If this is set to True, the axes which are reduced are left',
  '    two array_like objects, ``(a_axes, b_axes)``, sum the products of',
  '    parent_index : list of int',
  'from . import umath as um',
  '    >>> np.isclose([1e10,1e-8], [1.00001e10,1e-9])',
  '    array([[5, 6, 7, 8, 9],',
  '    array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])',
  '    array([0.25,  0.25])',
  '    --------',
  '    if isinstance(a, np.matrix):',
  '    For example, ``axes = 2`` is the equal to',
  '    printed decimals:',
  '        at least a sufficient number of bits for `num` to be represented in',
  '        dtype = dt',
  '    out : ndarray',
  '    >>> np.binary_repr(3)',
  '        Overrides the data type of the result.',
  'def _needs_add_docstring(obj):',
  '    The indexing works on the flattened target array. `put` is roughly',
  '            if obj.dtype.names is not None:',
  '    if include_initial:',
  '    axis : int',
  '    >>> b',
  '        A new array holding the result is returned unless `out` is',
  '    Returns',
  '    if min is None and max is None:',
  '        Output array, containing the indices of the elements of ``a.ravel()``',
  '        if shapesize < 0:',
  '    >>> import numpy as np',
  '            twocomp = 2**(poswidth + 1) + num',
  '    >>> import numpy as np',
  '    tup : sequence of ndarrays',
  '    However, often numpy will use a  numerically better approach (partial',
  '        ret = ret / rcount',
  '    new_size = 1',
  '    array([1, 3])',
  '           +===================+======================+',
  '        be of the appropriate shape and dtype. Note that `out` is always',
  '           +-------------------+----------------------+',
  '    Notes',
  '    --------',
  '        # copy behavior of record.__getattribute__,',
  '        return shape, slices, arrays',
  '    a : array_like',
  '    array([1, 1, 1, 1, 1, 1])',
  '    ndarray.sort : Inplace sort.',
  '    to select `atol` for the use case at hand, especially for defining the',
  '    """Given array shapes, return the resulting shape and slices prefixes.',
  '        if necessary to fill out the required number of elements.  The',
  '    -------',
  '        Values are rounded towards ``-inf`` instead of ``0`` when an',
  '    >>> np.cumsum(a,axis=1)      # sum over columns for each of the 2 rows',
  '    References',
  '            div = rcount',
  '    >>> a = np.array([1, 2, 3])',
  '    Using the mean keyword to save computation time:',
  '        to existing slice tuple without creating a new tuple every time.',
  '        a = shape_base.atleast_1d(a)',
  '    ----------',
  '            "Calling np.sum(generator) is deprecated, and in the future will "',
  '    a : array_like',
  '           | ``-arr.ndim``     | 0                    |',
  '    `side`  returned index `i` satisfies',
  '    ddof : {int, float}, optional',
  '        with the last axis index changing fastest, back to the first',
  '    >>> grid[1]        # column indices',
  '                  is the equivalent.',
  '    stop : array_like',
  '        Array of indices into the array. It has the same shape as `a.shape`',
  '    return _wrapfunc(a, \'transpose\', axes)',
  '    Offset into a memmap:',
  '    atleast_2d, atleast_3d',
  'def _vhstack_dispatcher(tup, *, dtype=None, casting=None):',
  '    >>> np.var(a)',
  '    You can also start the product with a value other than one:',
  '        ary = asanyarray(ary)',
  '    inner',
  '        initial_shape = list(x.shape)',
  '            return object.__getattribute__(self, attr)',
  'from contextlib import nullcontext',
  '    >>> b = np.array([[1, 2, 3], [4, 5, 6]])',
  '            "Number of samples, %s, must be non-negative." % num',
  '    >>> import numpy as np',
  '    new array',
  '    offset : int, optional',
  '    array(-3)',
  '            self.dtype = self.dtype',
  '        Discrete cross-correlation of `a` and `v`.',
  '    `nan` values. The enhanced sort order is documented in `sort`.',
  '    array([[1, 1, 1],',
  '        array is flattened before shifting, after which the original',
  '    Returns',
  '    >>> import numpy as np',
  '        If this is set to True, the axes which are reduced are left in the',
  'from .._utils import set_module',
  'def add_newdoc(place, obj, doc, warn_on_python=True):',
  '           [9, 5, 6, 7, 8]])',
  '    >>> np.mean(b)',
  '        fielddict = nt.void.__getattribute__(self, \'dtype\').fields',
  '    nanmax, maximum, fmax',
  '@array_function_dispatch(_ravel_dispatcher)',
  '        greater than 1-D.  The default order is \'C\'.',
  '    0.0',
  '    can have dimensions 2 or 3.  Where the dimension of either `a` or `b` is',
  '            dtype = sb.dtype(formats, aligned)',
  '        The type of the returned array and of the accumulator in which the',
  '        if result.ndim == 0:',
  '    "Bessel\'s correction" because it corrects for bias (toward lower values)',
  '    >>> np.choose(a, choices)',
  '        If the default value is passed, then `keepdims` will not be',
  'def _geomspace_dispatcher(start, stop, num=None, endpoint=None, dtype=None,',
  '    ...                         (\'Aadi\', 66.6, 6)], dtype=grades_dtype)',
  '            # fast-path for default case when where is True',
  '    >>> np.stack(arrays, axis=1).shape',
  '    flattened array by default, otherwise over the specified axis.',
  '        The axis for the calculation of the mean should be the same as used in',
  '    type(dtype(nt.int64)),',
  '    dtype : str or dtype',
  '    >>> arr2 = np.stack(np.unstack(arr, axis=1), axis=1)',
  '    between `a` and `b`.',
  '    Return a new array with the specified shape.',
  '    probability theory, the sum of two independent random variables is',
  '    choices : sequence of arrays',
  '        Fortran-style.  This only has an effect if the shape is',
  '    Contains boundary effects, where zeros are taken',
  '            negative(cp1, out=cp1)',
  '        Alternative output array in which to place the result. It must have',
  '    searchsorted : Find elements in a sorted array.',
  '_ones_with_like = array_function_dispatch()(ones)',
  '        Array of the same type and shape as `a`.',
  '           [[5, 6],',
  '        the returned array.',
  '        The returned array has the same type as `a`.',
  '    logspace : Similar to `geomspace`, but with the end points specified as',
  '    corresponding elements in `v` were inserted before the indices, the',
  '    Many other libraries define the variance of an array differently, e.g.:',
  '    of the array, using ``arr.x`` and ``arr.y``.',
  '    --------',
  'def partition(a, kth, axis=-1, kind=\'introselect\', order=None):',
  '    >>> np.count_nonzero(a, axis=1)',
  '        return res[0]',
  '    >>> a.tofile(fd)',
  '    3.0',
  '    bin : str',
  '    return umr_prod(a, axis, dtype, out, keepdims, initial, where)',
  '    if keepdims is not np._NoValue:',
  '        Position in the file to start reading from.',
  '    The various selection algorithms are characterized by their average',
  'def _prod_dispatcher(a, axis=None, dtype=None, out=None, keepdims=None,',
  '    Examples',
  '        Buffer (`buf`) is interpreted according to these strides (strides',
  'def _std_dispatcher(a, axis=None, dtype=None, out=None, ddof=None,',
  '        Axis or axes along which to operate.  By default, flattened input is',
  '    Examples',
  '    retstep : bool, optional',
  '    result *= out_sign',
  '    processing texts [1]_:',
  '    array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])',
  '    * if ``mode=\'clip\'``, values in `a` (and thus ``Ba``) may be any (signed)',
  '    --------',
  '    array([1, 2, 3, 4])',
  '    keepdims : bool, optional',
  '    Return a string representation of a number in the given base system.',
  'True_ = nt.bool(True)',
  '        but the type will be cast if necessary. See :ref:`ufuncs-output-type`',
  '        When you delete a memmap object, flush is called first to write',
  '        length `num`) are returned.',
  '    -------',
  'def ones(shape, dtype=None, order=\'C\', *, device=None, like=None):',
  '        detailed documentation.',
  '    via add_docstring.',
  '    \'101\'',
  '        dtype = mu.dtype(\'f8\')',
  '    lib.format.open_memmap : Create or load a memory-mapped ``.npy`` file.',
  '        order=\'C\' is implied.',
  '            shape = len(recList)',
  '    if dtype is None:',
  '    This example shows that a negative value can be returned when',
  '        a list of format description strings  in the form',
  '@array_function_dispatch(_repeat_dispatcher)',
  '    >>> np.min(a, where=[False, True], initial=10, axis=0)',
  '            self.offset = offset',
  '    try:',
  '@array_function_dispatch(_ptp_dispatcher)',
  '    -------',
  '    --------',
  '    full_like : Return a new array with shape of input filled with value.',
  '        Input array. If `sorter` is None, then it must be sorted in',
  '        res = _sum_(a)',
  '    """A data-type scalar that allows field access as attribute lookup.',
  '    keyword can alleviate this issue.',
  '            self._mmap = mm',
  '    array([1, 2, 3])',
  '        If provided, the destination array will have this dtype. Cannot be',
  '    Note that the order in which the diagonal is retrieved varies depending',
  '    In some future release, it will return a read/write view and writing to',
  '    --------',
  '    Returns',
  '    array([[0., 1.],',
  '        # non-structured, convert it to an ndarray. Then if obj is structured',
  '    True',
  '            "Input should be a NumPy array or scalar. "',
  '    precision for the output.',
  '        \'valid\':',
  '    a = asarray(a)',
  '    return _wrapfunc(a, \'argmin\', axis=axis, out=out, **kwds)',
  '    ----------',
  '    >>> import numpy as np',
  '        :term:`row-major`, C-style or :term:`column-major`,',
  '    ...               [0, 0, 0]])',
  '        .. versionadded:: 2.0.0',
  '    True',
  '    --------',
  '    ...     dtype=np.dtype([(\'a\', np.int32), (\'b\', \'S3\'), (\'c\', np.float32)]))',
  '    # As a special case, dimension 0 of 1-dimensional arrays is "horizontal"',
  '            new = obj.view(dtype)',
  '    Returns',
  '@array_function_dispatch(_astype_dispatcher)',
  '            if offset:',
  '    if isinstance(new_shape, (int, nt.integer)):',
  '    if x.ndim < 2:',
  '        The shape and data-type of `a` define these same attributes of',
  '    ...               # total product 1*2*3 = 6',
  '    b0 = b[..., 0]',
  '    >>> np.ptp(x, axis=0)',
  '        _array = recarray(shape, descr)',
  '    \'asfortranarray\', \'zeros\', \'count_nonzero\', \'empty\', \'broadcast\', \'dtype\',',
  '    nt.dtype(nt.csingle) : nt.dtype(nt.single),',
  '    any : bool or ndarray',
  '        The shape and data-type of `a` define these same attributes of',
  '@set_module(\'numpy\')',
  '    def __getitem__(self, indx):',
  '        passed through to the `std` method of sub-classes of',
  '@array_function_dispatch(_flatnonzero_dispatcher)',
  '            pass',
  '    See Also',
  '    Parameters',
  '    2, the third component of the input vector is assumed to be zero and the',
  '        the result is returned.',
  '        Vector cross product(s).',
  '        If this is a tuple of ints, a reduction is performed on multiple',
  '        return um.clip(a, min, max, out=out, **kwargs)',
  '        Input values.',
  '        means to read / write the elements using C-like index order,',
  '    array([ True, False])',
  '    elif isinstance(shape, int):',
  '    >>> np.cumulative_prod(b, axis=0)',
  '                return reduction(axis=axis, out=out, **passkwargs)',
  '            if len(index) != len(first_index):',
  'from .arrayprint import *',
  '    See Also',
  '        The shape that the final array will take on.',
  '    >>> import numpy as np',
  '    dtype : data-type, optional',
  'def geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0):',
  '          By default, mode is \'full\'.  This returns the convolution',
  '        (None) is to compute the cumsum over the flattened array.',
  '    return _array',
  '    `block` provide more general stacking and concatenation operations.',
  'def fromfile(fd, dtype=None, shape=None, offset=0, formats=None,',
  '    -------',
  '    dstack : Stack arrays in sequence depth wise (along third axis).',
  '    axis : int, optional',
  '           [3, 4],',
  '    return \'\'.join(reversed(res or \'0\'))',
  '    >>> import numpy as np',
  '    front. If width is given, the two\'s complement of the number is',
  '    ndarray.any : equivalent method',
  '    """',
  '    """',
  '    samples : ndarray',
  '    new = getattr(__import__(place, globals(), {}, [obj]), obj)',
  '    array([ True,  True])',
  '        An array having the specified data type.',
  '        then the size of `axis` will be 1 with the resulting array having same',
  '        binary = bin(num)[2:]',
  '        sorting. The default is -1, which sorts along the last axis.',
  '    # Ensure that num is a Python integer to avoid overflow or unwanted',
  '    Notes',
  '    ------',
  '    (MATLAB behavior), please use nanmax.',
  '            result = ary',
  '        return new',
  '    Construct an array from an index array and a list of arrays to choose from.',
  '    >>> x = [1,2]',
  '    >>> np.round([1,2,3,11], decimals=1) # ndarray of ints is returned',
  '    else:',
  '    >>> x = np.array([[4,2,3], [1,0,3]])',
  '        order in which they come up in the dtype, to break ties.',
  '    a : array_like',
  '    return _wrapreduction(a, np.minimum, \'min\', axis, None, out,',
  '        If True, align the fields by padding as the C-compiler would.',
  'def block(arrays):',
  '    array([[0, 1],',
  '    row-major, C-style order.',
  '    >>> # Same as np.amax(x, axis=-1)',
  '    ...',
  'from . import numerictypes as nt',
  '    Round an array to the given number of decimals.',
  '    except TypeError:',
  '    >>> import numpy as np',
  '        result has the same shape as ``x`` if ``include_initial=False``.',
  '    (3, 1)',
  '    ----------',
  '           [1, 1],',
  '    use one of the following methods:',
  '        List of array-like objects (such as lists, tuples,',
  '        In that case, ``num + 1`` values are spaced over the',
  '    If the type of `x` is unsigned, then the output type is',
  '    arrs = atleast_1d(*tup)',
  '        but unspecified fields will still be used, in the order in which',
  '    nonzero : Return the coordinates of all the non-zero values.',
  '            # or if it has a scalar (non-void) dtype with no records,',
  '    array([10, 11, 12, 13, 10, 15])',
  '        ).dtype',
  '    resource is actually closed, since it may be shared between different',
  '        a1, a2 = asarray(a1), asarray(a2)',
  '    dtype : dtype',
  '        These are called slice prefixes since they are used in the recursive',
  '    kwargs = {}',
  '    final_size: int',
  '    axes.remove(axis)',
  '    """',
  '    Returns',
  '    Parameters',
  '    Computing the standard deviation in float64 is more accurate:',
  '    mode : {\'raise\', \'wrap\', \'clip\'}, optional',
  '    else:',
  'def roll(a, shift, axis=None):',
  '    """',
  '        cccDD',
  '    a : array_like',
  '            return obj.view((self.__class__, obj.dtype))',
  '# These helper functions are mostly used for testing.',
  '    array([[1, 1],',
  '    .. versionchanged:: 2.0',
  '           "(dimension must be 2 or 3)")',
  '    Returns the standard deviation, a measure of the spread of a distribution,',
  '    """',
  '        `ndarray`, however any non-default value will be.  If the',
  '    array([[1, 4],',
  '    True',
  '        has an integer dtype of less precision than the default platform',
  'def isfortran(a):',
  '    ndarray.reshape : Equivalent method.',
  '    >>> np.isscalar(Number())',
  '    See also',
  '    ndarray.min : equivalent method',
  '           [False, False,  True]])',
  '    return (a, a_min, a_max, out, min, max)',
  '    if bottom_index and bottom_index[-1] is None:',
  '    ``a[:, np.newaxis]``.',
  '        raise ValueError("Bases less than 2 not handled in base_repr.")',
  '@array_function_dispatch(_count_nonzero_dispatcher)',
  '    if isinstance(ret, mu.ndarray):',
  'def max(a, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue,',
  '    >>> np.allclose([1e10,1e-7], [1.00001e10,1e-8])',
  '    There are several common variants of the array variance calculation.',
  '        If `a` is one-dimensional, ``a[index_array]`` yields a sorted `a`.',
  '    Indices of the minimum elements of a N-dimensional array:',
  '            [-1, -2, -3, -4, -5]]])',
  '        Choice arrays. `a` and all of the choices must be broadcastable to the',
  '        in the result as dimensions with size one. With this option,',
  '    >>> np.correlate([1, 2, 3], [0, 1, 0.5], "same")',
  '    Returns',
  '    kind : {\'quicksort\', \'mergesort\', \'heapsort\', \'stable\'}, optional',
  '        This tuple satisfies::',
  '        Input array.',
  'numfmt = nt.sctypeDict',
  '    ``a.mean()``, NumPy computes the standard deviation of an array as::',
  '        Valid dtype for array.',
  '        in the result as dimensions with size one. With this option,',
  '    if not equal_nan:',
  '    """',
  '        # axis and full sum is more excessive than needed.',
  '    Examples',
  '            var = a.var',
  '    if a.shape[-1] == 3:',
  '    >>> plt.plot(x1, y, \'o\')',
  '    if dtype is None:',
  '    numpy.reshape : Reshape an array without changing the total size.',
  '        if isinstance(formats, list):',
  '    Notes',
  '        this option selects ``kind=\'stable\'``. Default: ``None``.',
  '    Returns',
  '    | other builtin objects, like        | ``False``     | ``True``          |',
  '    -----',
  '    -------',
  '    yield from choices',
  '_complex_to_float = {',
  '            if bytes == 0 and start > 0:',
  '    compressed_array : ndarray',
  '        Overrides the shape of the result. If order=\'K\' and the number of',
  '        Array of ones with the same shape and type as `a`.',
  '    where : array_like of bool, optional',
  '        >>> round(56294995342131.5, 3)',
  '    Returns',
  'from . import arrayprint',
  '@array_function_dispatch(_mean_dispatcher)',
  '           [3, 4, 0, 1, 2]])',
  '        The absolute tolerance parameter (see Notes).',
  '        An array of the same type as `a`, containing the rounded values.',
  '        `numpy.format_parser` to construct a dtype. See that function for',
  '        kwargs[\'mean\'] = mean',
  '@array_function_dispatch(_cumulative_sum_dispatcher)',
  '    ----------',
  '    (array([0, 1, 1, 0]), array([0, 0, 1, 1]))',
  '    >>> b = np.array([4, 5, 6])',
  '    elif formats is not None:',
  '_no_nan_types = {',
  '        import os.path',
  '        return _identity_with_like(like, n, dtype=dtype)',
  '    dtype : data-type, optional',
  '    mgrid, ogrid, meshgrid',
  '        One shape dimension can be -1. In this case, the value is',
  '            "fromrecords expected a list of tuples, may have received a list "',
  '      [2]]] (1, 2, 1)',
  '        # get data/shape string. logic taken from numeric.array_repr',
  '        warnings.warn(',
  '    keepdims : bool, optional',
  '    [[[1]',
  '    ----------',
  '           [5, 6, 0]])',
  'import warnings',
  '    warn_on_python : bool',
  '        given axis.',
  '    array([[False, False, False],',
  '        kwds = {\'formats\': formats,',
  '    a : array_like',
  '        axis is negative it counts from the last to the first axis. If',
  '        blocking algorithm to compute the left-most slices during the',
  '    (array([1]), array([3, 4]))',
  '            except AttributeError:',
  '    -----',
  '        If sparse is False:',
  '    \'searchsorted\', \'shape\', \'size\', \'sort\', \'squeeze\',',
  '        # if the names are not specified, they will be assigned as',
  '    ======  ============================',
  '    >>> np.argmax(a, axis=1)',
  '        obj = nt.void.__getitem__(self, indx)',
  '            [20, 21, 22, 23]]))',
  '    This function makes most sense for arrays with up to 3 dimensions. For',
  '    --------',
  '    >>> np.sort(a, order=\'height\')                        # doctest: +SKIP',
  '    if (dtype := getattr(y, "dtype", None)) is not None and dtype.kind != "m":',
  '    >>> np.block([b])                    # atleast_1d(b)',
  '    >>> np.take_along_axis(x, np.expand_dims(index_array, axis=-1), axis=-1)',
  '        that this disables indexing with negative numbers.',
  '        for more details.',
  '        arrs = [_block(arr, max_depth, result_ndim, depth+1)',
  '            result = ary[:, :, _nx.newaxis]',
  '        descr = format_parser(formats, names, titles, aligned, byteorder).dtype',
  '            # a0 * b1 - a1 * b0',
  '    >>> np.min(a)           # Minimum of the flattened array',
  '    ndarray.take : equivalent method',
  '        If the dimension of `a` is less than 2.',
  '    x_ndim = x.ndim',
  '    ind : array_like',
  '    index_array : ndarray of ints',
  '    >>> N = 10',
  'import numpy as np',
  '            [7, 8]]])',
  '    axis : int or None, optional',
  '    Each output sample is a constant multiple of the previous.',
  '            new = new.copy()',
  '    >>> b',
  '    return(like,)',
  '        Copies are avoided where possible, and views with two or more',
  '        \'56294995342131.5\'',
  '    """',
  'little_endian = (sys.byteorder == \'little\')',
  '           [3, 4]])',
  '    full_like : Return a new array with shape of input filled with value.',
  '        raise ValueError(\'a cannot be empty\')',
  '@array_function_dispatch(_clip_dispatcher)',
  '    | PEP 3141 numeric objects           | ``True``      | ``True``          |',
  '    >>> a = [[1, 0, 1], [0, 1, 0], [1, 0, 1]]',
  '    # Use `dtype=type(dt)` to enforce a floating point evaluation:',
  '        preserved.',
  '                raise',
  '           [[[15, 18],',
  '            elif hasattr(fid, "name") and isinstance(fid.name, str):',
  '              dtype=int64)',
  '    .. warning:: The default `atol` is not appropriate for comparing numbers',
  '        # Deprecated in NumPy 2.1, 2024-04-18',
  '           [[4, 5],',
  '    -------',
  '    a : array_like',
  'def zeros_like(',
  'from ._asarray import *',
  '    >>> import numpy as np',
  '        on large arrays.',
  '    else:',
  '        dimensions is unchanged, will try to keep order, otherwise,',
  '            [6, 8]]])',
  '    properties:',
  '    -----',
  '    -----',
  '    Binary search is used to find the required insertion points.',
  '    --------',
  '        in the result as dimensions with size one. With this option,',
  '    >>> np.cumulative_prod(b, axis=1)',
  '    `binary_repr` is equivalent to using `base_repr` with base 2, but about 25x',
  '    binary_repr : Faster version of `base_repr` for base 2.',
  '    >>> A = np.ones((2, 2), int)',
  '    This function continues to be supported for backward compatibility, but you',
  '    if hasattr(file, \'write\'):',
  '    >>> np.min(b, where=~np.isnan(b), initial=10)',
  '    Compute the standard deviation along the specified axis.',
  '    -----',
  '        na = len(axes_a)',
  '    Parameters',
  '    ----------',
  '       [ ...          .',
  '        The function is called with N parameters, where N is the rank of',
  '    See Also',
  '@set_module(\'numpy\')',
  '    elif hasattr(ret, \'dtype\'):',
  '            return arr',
  '        If specified, all the fields will be changed to the',
  '    return (a, b, rtol, atol)',
  '__all__ = [\'atleast_1d\', \'atleast_2d\', \'atleast_3d\', \'block\', \'hstack\',',
  '           +-------------------+----------------------+',
  '            [ 8,  9, 10, 11]]),',
  '    `output` for each index where `condition` evaluates to True. When',
  '        Array of zeros with the same shape and type as `a`.',
  '        Array of `fill_value` with the given shape, dtype, and order.',
  '    array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])',
  '    >>> a[1, :] = 0.1',
  '    >>> x = np.array([1, 2, 3], dtype=np.uint8)',
  '    >>> np.full((2, 2), [1, 2])',
  '        else:',
  '    >>> a = np.array([[14, 8, 11, 10], [7, 9, 10, 11], [10, 15, 5, 10]])',
  '            else:',
  '    >>> np.take_along_axis(x, index_array, axis=-1)',
  '    Notice that the initial value is used as one of the elements for which the',
  '    Parameters',
  '      [2]]] (1, 2, 1)',
  '        Whether to compare NaN\'s as equal. If the dtype of a1 and a2 is',
  '    (array(True), array(True))',
  '    `dtype` keyword can alleviate this issue.',
  '    of repeated copies of `a`.',
  '    This constructor can be compared to ``empty``: it creates a new record',
  '    >>> np.isfortran(a)',
  '    >>> a = np.array([[1, 2], [3, 4]])',
  '    array([1, 2, 3])',
  '        # flatten returns (1, N) for np.matrix, so always use the last axis',
  '    arrays : nested list of array_like or scalars (but not tuples)',
  '           [3, 4, 5]])',
  '    a : array_like',
  '    return _nx.power(base, y).astype(dtype, copy=False)',
  '               in linear space, instead of log space.',
  '        If `out=None`, returns a new array containing the mean values,',
  '    array([2, 2])',
  '        if copy:',
  '    array([[1],',
  '    cp = empty(shape, dtype)',
  '    --------',
  '    normalize_axis_index : normalizing a single scalar axis',
  '    ----------',
  '    except Exception:',
  '    >>> x[ind]  # same as np.sort(x, axis=None)',
  '        required to be prepended with ``(Ellipsis, )`` to obtain to correct',
  '    ndarray.shape : dimensions of array',
  '        imaginary component of a given value is ``nan``.',
  '    -----',
  'from . import numerictypes',
  '        There are `num` equally spaced samples in the closed interval',
  '    Replaces specified elements of an array with given values.',
  '    max_arr_ndim : int',
  '                # special case - if we were constructed with a pathlib.path,',
  '    array([ 0, 10])',
  '    """',
  '               names=None, titles=None, aligned=False, byteorder=None):',
  '    >>> np.cross(x, y)',
  '        ``out[i, j] = a[i] * b[j]``',
  '    >>> a = np.array([(1, 2), (3, 4), (5, 6)],',
  '    numpy.repeat : Repeat elements of an array.',
  '    to a very small or zero value in `b`.',
  '    # nonzero does not behave well on 0d, so promote to 1d',
  '        to hold the output.  Its type is preserved.',
  '    >>> np.sort(a)                # sort along the last axis',
  '    >>> np.ndim([[1,2,3],[4,5,6]])',
  '    msg = "\'%s\' arg requires %d <= %s < %d, but %d was passed in"',
  '         where=np._NoValue):',
  '        which fields to compare first, second, etc.  A single field can',
  '    except Exception:',
  '    def __array_finalize__(self, obj):',
  '        If defined, the axis of `a`, `b` and `c` that defines the vector(s)',
  '    See Also',
  '        order=\'C\' is implied.',
  '    AxisError',
  '    """',
  '    Parameters',
  '    Notes',
  '    >>> np.array_equiv([1, 2], [1, 3])',
  '    """',
  '        # it\'s been removed',
  '    array([[0, 1],',
  '                    "shape and type."',
  '    array([ True, True])',
  '    if where is True:',
  '        res = np.concat(',
  '            self._titles = [n.strip() for n in titles[:self._nfields]]',
  '    """',
  '    --------',
  'def _var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False, *,',
  '    try:',
  '    Don\'t use `~numpy.max` for element-wise comparison of 2 arrays; when',
  '    True',
  '        return asarray(a).ndim',
  '        # exception has a traceback chain.',
  '    >>> B = 2 * A',
  'def _searchsorted_dispatcher(a, v, side=None, sorter=None):',
  '    transpose : Permute the dimensions of an array.',
  '    >>> import numpy as np',
  '    r"""',
  '    """',
  '    >>> np.take_along_axis(x, np.expand_dims(index_array, axis=-1),',
  '    array([4.        ,  5.0396842 ,  6.34960421,  8.        ])',
  '    `vsplit`.',
  '        if shape is not None:',
  '    take_along_axis : Apply ``index_array`` from argpartition',
  '        The starting value of the sequence.',
  '    try:',
  '    working on a 1-D array, `compress` is equivalent to `extract`.',
  '    >>> a[0, :] = 1.0',
  '                         **kwargs)',
  '    return tuple(arrays)',
  'def cumprod(a, axis=None, dtype=None, out=None):',
  '    dtype : data-type, optional',
  '    out : ndarray, optional',
  '    >>> np.max(b, where=~np.isnan(b), initial=-1)',
  '        Size of spacing between samples.',
  '    elif type(arrays) is list and len(arrays) == 0:',
  '    These all achieve the same result:',
  '            ``grid.shape = (len(dimensions),) + tuple(dimensions)``.',
  '    equal to ``p2[8]``.  The partition is::',
  '        Target indices, interpreted as integers.',
  '    Warning: This functionality does **not** consider axes separately,',
  '        result = asanyarray(ary)',
  '    >>> y = np.zeros(N)',
  '    True',
  '    >>> np.repeat(x, 3, axis=1)',
  '    -------',
  '    partitioning along any but the last axis.  Consequently,',
  '    cumulative_prod_along_axis : ndarray',
  '        type of `a`, otherwise it will be a base-class array. Defaults',
  '    >>> r.col2',
  '    \'newaxis\', \'ndarray\', \'flatiter\', \'nditer\', \'nested_iters\', \'ufunc\',',
  '        ``[\'f8\', \'i4\', \'S5\']``.',
  '            [20, 21, 22, 23]]))',
  '    hstack : Stack arrays in sequence horizontally (column wise).',
  '    Computing the variance in float64 is more accurate:',
  '    Examples',
  '    condition : 1-D array of bools',
  '    [<matplotlib.lines.Line2D object at 0x...>]',
  '           [-2.-2.j, -1.-2.j,  0.-2.j,  1.-2.j,  2.-2.j]])',
  '        Axis along which to sort.  The default is -1 (the last axis). If None,',
  '        # Flatten the array list',
  '        Shape of output array.',
  '          dtype=[(\'name\', \'|S10\'), (\'height\', \'<f8\'), (\'age\', \'<i4\')])',
  '           [5, 7, 9]])',
  '    `numpy.ndarray.astype`.',
  '    x : ndarray',
  '            negative(cp0, out=cp0)',
  '    >>> r.col1',
  '            [\'aaacccc\', \'bbbdddd\']],',
  '    True',
  '    Notes',
  '        Path to the mapped file.',
  '        An empty list can be used, in that case default field names',
  '    >>> np.std(a)',
  '           [1, 1, 1]])',
  '    --------',
  '            # support a dtype.',
  '        if isinstance(obj[0], (tuple, list)):',
  '    return _methods._ptp(a, axis=axis, out=out, **kwargs)',
  '          ``N>=1``.',
  '                    object.__delattr__(self, attr)',
  '    ndarray.argmin, argmax'
];
